<a href="https://colab.research.google.com/github/ghinanto/gnn_gw/blob/main/o4b_0_Triggers_and_Injections_Tutorial.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# SETUP

In [43]:
%matplotlib inline
# if error run twice
! pip install -q pandas scipy matplotlib scikit-learn pycbc==2.8

In [44]:
# import libraries
import pycbc
import pandas as pd
import os
import matplotlib.pyplot as plt
import numpy as np

In [45]:
pd.set_option('display.float_format', '{:}'.format)#format to not have scientific notation. Add {:.4e} to have four decimals

# o4b-0 triggers from Sarah with configuration:


```
configuration = {
"window": 512,
"overlap":16, #here same region is covered 4 times, try lower
"threshold": 0.5,
"file": tmpffl,
"channel": ifo+"1:STRAIN_BURST_0",
"run":"full_print3",
"len":10.0,
"dir": '/srv/beegfs/dpnc/groups/gw/sarah/wdf_playground/',
"outdir": '/srv/beegfs/dpnc/groups/gw/sarah/wdf_playground/',
"ID":"WDF_test_"+ifo+"1_0",
"ARorder": 2000, # because real noise (fake noise 1k ok)
"learn": 200,
"preWhite":3,
"ResamplingFactor":8,
"LowFrequencyCut":12,
"FilterOrder":6,
"nproc":14,
'itf':ref,
"gps": min(after_veto)[0],
'lastGPS': max(after_veto)[1],
"segments":after_veto
}
```

Getting triggers from public repo (https://github.com/ghinanto/gnn_gw.git):

In [46]:
# get triggers from repo
triggers_files = {'H': "https://raw.githubusercontent.com/ghinanto/gnn_gw/refs/heads/main/triggers_hanford.csv", 'L': "https://raw.githubusercontent.com/ghinanto/gnn_gw/refs/heads/main/triggers_livingston.csv"} #, 'V': "triggers_virgo.csv"}
itf_sites_list = ['H', 'L'] #, 'V']
# read triggers in dataframe
triggers_df = {}
for ITF in itf_sites_list:
    triggers_df[ITF] = pd.read_csv(triggers_files[ITF])
#print(df_itf_data)

## How to access triggers

`triggers_df` is a dictionary containing a different trigger dataframe for each itf

In [47]:
triggers_df['H']

,gps,gpsPeak,duration,EnWDF,snrMean,snrPeak,freqMin,freqMean,freqMax,freqPeak,...,wt502,wt503,wt504,wt505,wt506,wt507,wt508,wt509,wt510,wt511
0,1402436049.859375,1402436050.0004883,0.0048828125,0.5207324367866512,0.4569136210357895,6.113423365875362,12.0,72.46153846153847,180.0,20.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,1402436059.7890625,1402436060.0,0.0244140625,0.8333744468137334,0.8569261079001252,10.631658182974729,24.0,74.0,124.0,36.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,1402436069.9609375,1402436070.0004883,0.01171875,1.4489854324471336,1.5769807067411394,18.53137287730165,8.0,69.53846153846153,120.0,36.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,1402436089.8203125,1402436090.0004883,0.02685546875,0.8175907082013761,0.870263113806825,8.870364063960707,8.0,83.38461538461539,156.0,20.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,1402436099.9921875,1402436100.0004883,0.01318359375,0.8634525556922379,1.0614104630719894,13.339421276071562,24.0,89.07692307692308,180.0,36.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14864,1402279653.7890625,1402279654.0205078,0.240234375,0.6376103790372831,0.3340220613253927,1.72929329681386,72.0,141.69230769230768,228.0,144.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
14865,1402279656.9375,1402279657.0009766,0.017578125,1.5854428242505152,1.3041864451838794,15.241391028578208,28.0,78.15384615384616,132.0,60.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
14866,1402279658.875,1402279658.8979492,0.24951171875,0.5454071035138536,0.3408257839064426,1.4236412301984829,52.0,119.6923076923077,232.0,124.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
14867,1402279666.8671875,1402279667.0009766,0.01123046875,3.735620755795916,2.5900528470415085,30.42279644782136,4.0,55.23076923076923,132.0,68.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
14868,1402279672.6796875,1402279672.7856443,0.10888671875,1.7428248599031009,1.1914725909470734,5.426179150330022,16.0,75.53846153846153,200.0,52.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [48]:
triggers_df['L']

,gps,gpsPeak,duration,EnWDF,snrMean,snrPeak,freqMin,freqMean,freqMax,freqPeak,...,wt502,wt503,wt504,wt505,wt506,wt507,wt508,wt509,wt510,wt511
0,1402310586.0,1402310586.0004883,0.24951171875,1.299206437227144,1.119918671545818,12.482401159000672,4.0,58.76923076923077,132.0,40.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,1402310625.9609375,1402310626.0009766,0.0048828125,1.6020211326571232,1.427294392842551,16.504489849454707,4.0,54.15384615384615,108.0,20.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,1402310645.8203125,1402310646.0004883,0.0771484375,0.5787349799362784,0.4837856732435328,5.742278108360163,8.0,94.0,176.0,20.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,1402310655.9921875,1402310656.0009766,0.2373046875,0.5999784829395222,0.5558256976162798,5.25676057950142,8.0,61.69230769230769,132.0,20.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,1402310695.953125,1402310696.0009766,0.01220703125,1.2702218612961107,1.282895189124556,15.256674714224424,4.0,54.0,104.0,36.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12981,1402309893.8359375,1402309894.0,0.0068359375,0.5088894446724356,0.4064057419960049,5.046473347680055,136.0,186.0,236.0,168.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
12982,1402336602.0,1402336602.0004883,0.24951171875,0.9254003473243436,0.8490432817498272,9.763185631435237,20.0,70.0,120.0,44.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
12983,1402336631.7890625,1402336632.0004883,0.02490234375,1.019829156698124,1.0075594838688458,11.543435159544972,24.0,74.0,124.0,36.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
12984,1402336651.890625,1402336652.0004883,0.00537109375,1.0524348968028765,1.115674552481518,12.944641992716017,12.0,62.0,112.0,20.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
12985,1402336661.8203125,1402336662.0,0.029296875,0.6372742689155554,0.6403611159031866,6.908903084453264,24.0,74.0,124.0,36.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

We select triggers depending on parameter values using masks:

In [49]:
IFO='H'
mask_test = triggers_df[IFO]['snrPeak'] > 80
triggers_df[IFO][mask_test]

,gps,gpsPeak,duration,EnWDF,snrMean,snrPeak,freqMin,freqMean,freqMax,freqPeak,...,wt502,wt503,wt504,wt505,wt506,wt507,wt508,wt509,wt510,wt511
146,1402439029.0078125,1402439029.142578,0.0107421875,10.317918583912004,7.868437255328175,83.62065384498014,72.0,122.0,172.0,108.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
223,1402440824.1015625,1402440824.2617188,0.2314453125,4.431651750479376,11.303230819884284,138.74602577376874,24.0,116.0,292.0,40.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
224,1402440824.34375,1402440824.4750977,0.02392578125,39.99544999197884,132.14993214059774,1154.086275614853,32.0,82.3076923076923,140.0,48.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
292,1402442400.7421875,1402442400.9223633,0.03271484375,5.780441399017173,6.568384699591329,84.0731763218118,124.0,186.92307692307693,244.0,168.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
293,1402442400.984375,1402442401.1484375,0.07666015625,9.613889039378645,11.728973486833077,104.6677823197756,32.0,99.6923076923077,196.0,48.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12790,1402255996.3671875,1402255996.5307617,0.00390625,3.487422131315905,4.211156568125961,83.93223817859406,164.0,266.0,352.0,316.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
12984,1402270962.890625,1402270963.0913086,0.0087890625,13.788513204576873,11.19270386441383,153.67551118171986,88.0,138.15384615384616,192.0,144.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
14668,1402278977.359375,1402278977.5839844,0.20947265625,13.919136499856316,15.502302370969383,126.02783311741992,32.0,138.0,284.0,60.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
14669,1402278977.6015625,1402278977.7827148,0.033203125,57.69906001120501,97.00403925802156,865.2708617923738,36.0,93.3846153846154,144.0,68.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
14672,1402278978.328125,1402278978.4697266,0.02587890625,18.51612425896433,24.02513800036868,208.7719427524553,24.0,74.61538461538461,132.0,36.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

# o4b-0 INJECTIONS

Download injections file from my dropbox (they are at CIT originally):

In [50]:
import requests

# Public sharing link
data_link = "https://www.dropbox.com/scl/fi/io7tz6z7w10p6c4l5vypb/burst_benchmark_short-0.h5?rlkey=xog18i7kls966dh4k3wh0f2z4&st=6fol2p3s&dl=1"
data_file = "burst_benchmark_short-0.h5"

# Download file
response = requests.get(data_link, allow_redirects=True, stream=True)
if response.status_code == 200:
    with open(data_file, "wb") as f:
        for chunk in response.iter_content(chunk_size=8192):
            f.write(chunk)
    print(f"File downloaded successfully as {data_file}")
else:
    print(f"Error: {response.status_code}, {response.text}")

File downloaded successfully as burst_benchmark_short-0.h5

Injection file refer to the entire o4b-2 (3months). Define start and end of **o4b-0** (3 days)

In [51]:
gpsStart_o4b0 = 1402200018
gpsEnd_o4b0 = 1402527618

The next cell read the `.h5` injection file and produces 3 objects (dictionaries) containing all the data in the form of DataFrames.

1.   `inj_parameters`: containing parameters of injections, e.g. time, ra, dec, etc. They vary for each injection type.
2.   `inj_attributes`: contining attributes of injections that is for the most only the injection type. If type is WAVE however, here you find also the `sampling_rate` and `hrss_norm` attributes.
3.   `inj_STRAIN_time_series`: only for type WAVE injections. Containing the time series defined by `hcross`, `hplus` and `time`. The size of this series (i.e. the number of samples) and the `sampling_rate` from `inj_attributes` gives the duration of the injection.

Let's run and talk about it with examples.

In [52]:
import h5py
import pandas as pd
import numpy as np

def inj_h5_to_df(inj_file):
  inj_parameters = {}
  inj_attributes = {}
  inj_STRAIN_time_series = {}
  #open file
  with h5py.File(inj_file, "r") as f:
    inj_wave_types = list(f.keys())

    # loop all inj types
    for inj_wave_type in inj_wave_types:
      # save parameters in dict
      inj_parameters[inj_wave_type] = pd.DataFrame(np.array(f[inj_wave_type]['PARAMETERS']))
      inj_attributes[inj_wave_type] = {inj_attr_key: inj_attr_val for inj_attr_key, inj_attr_val in zip(list(f[inj_wave_type].attrs), list([f[inj_wave_type].attrs[attr] for attr in f[inj_wave_type].attrs]))}

      if f[inj_wave_type].attrs['type'] == 'WAVE':
        # save other attrs
        # dataframe with columns of strain_pars
        inj_STRAIN_time_series[inj_wave_type] = pd.DataFrame()
        for strain_par in f[inj_wave_type]['STRAIN']:
          inj_STRAIN_time_series[inj_wave_type][strain_par] = np.array(f[inj_wave_type]['STRAIN'][strain_par]) # build columns of a dataframe with
    return inj_parameters, inj_attributes, inj_STRAIN_time_series

In [53]:
inj_parameters, inj_attributes, inj_STRAIN_time_series = inj_h5_to_df(data_file)

So each of them is a dictionary having injection wave types as keys, e.g. 'cbc_bbh10', 'ccsn_oco18_mesa20pertlr', 'sg_235q100'. Let's print `inj_parameters`:

In [54]:
inj_parameters

{'cbc_bbh10':                   time                 ra                   dec  \
 0   1401544616.6077347 0.6827237915976532 -0.002122447397676227
 1   1401549018.8499951  3.293118558923391  0.018214685256745498
 2    1401549361.914258 2.1744442699842184   0.13820620189023927
 3   1401560966.6830468  6.033871590690589    -0.232330463206306
 4   1401563965.2646575  3.173639928987707  -0.20820676987776812
 ..                 ...                ...                   ...
 312 1403872401.1521857  5.402287239269025  -0.36509205549652246
 313  1403879908.391154  4.177788537859473    -1.176994094810024
 314 1403887584.3378274  4.207592299758727     0.568964308094855
 315 1403911011.6065469 1.4534266023218212    0.2283586802122033
 316  1403963810.611586  2.024254197243319  -0.05115205979735421

                    pol          amplitude   seed
 0   2.4302941755495318  4.317994755509715 5533.0
 1    5.380765731268311  1.783393898391357 5533.0
 2   1.2714437895819604  2.104221223293229 5533.0
 3   3.2232957566438643 10.352765576021536 5533.0
 4     1.55741115234903  7.909681753115358 5533.0
 ..                 ...                ...    ...
 312  4.971374621816503  2.204562682410836 5533.0
 313  5.517719118504674 1.4470594537561916 5533.0
 314 0.6891267409868657  5.530106155211455 5533.0
 315  3.055591619242568  4.711991296919104 5533.0
 316  5.299315438660485 12.615518631004623 5533.0

 [317 rows x 6 columns],
 'cbc_bbh125':                   time                 ra                  dec  \
 0   1401558234.6129146  3.194669150079345  -0.2485258013124196
 1   1401563256.0528705 4.5909902434964955  -0.3195380464517017
 2   1401576188.9293673  1.830501141343262   -0.270309990011327
 3   1401583113.5425642  2.585016200386482  0.29755878957899445
 4   1401595901.0154781  4.244148602849464  -0.9504771910310322
 ..                 ...                ...                  ...
 336 1403893070.8917227    1.5933128308627  -0.6135818871891542
 337 1403914576.7568765  0.897932287578325  0.08356610567907934
 338 1403920981.8818045  4.764681988205142 -0.07746168702099199
 339 1403930956.1165135 2.6237625640919613   0.2783407812084188
 340 1403947036.3046224  5.755416240052322 -0.34346409573454356

                    pol          amplitude   seed
 0   2.4668665439616064 17.742113536975584 5533.0
 1    4.221318203762664   140.148199856269 5533.0
 2    4.495836953640261 28.414073846252013 5533.0
 3   2.7109687484506724   42.3516728787371 5533.0
 4   2.3310140915904665  39.35239713315597 5533.0
 ..                 ...                ...    ...
 336  1.149046404031767  65.06692382297007 5533.0
 337 4.7746279966680225 159.98899547622676 5533.0
 338  3.145941889438117  40.68702268885946 5533.0
 339 2.2040956218198495 36.771268278583136 5533.0
 340 3.7692845349286963  87.46082282289274 5533.0

 [341 rows x 6 columns],
 'cbc_bbh35':                   time                  ra                   dec  \
 0   1401557011.0172358  0.8509743487440908      0.98424456583635
 1   1401592710.6198723   3.546602326338775   0.08600891444150358
 2   1401592803.6239839 0.28937368111651746  -0.05087737746063265
 3    1401598280.916562   5.680092044397289    0.6309061902568324
 4    1401601240.268674 0.23696212206330505    0.5715296781892867
 ..                 ...                 ...                   ...
 303  1403911652.329696    5.85553287563027 0.0027477330083065265
 304  1403912660.501775  3.0506998108927617  -0.02095986549299163
 305  1403941262.528807  1.7014827480611534  0.058603027920405025
 306  1403951686.039029  1.0343420868727495    0.4435612976007591
 307 1403958931.4022644  4.6947660338985715   -0.1876358672042031

                    pol          amplitude   seed
 0   2.8351200363803604 1.1101032763577288 5533.0
 1   1.4776595349255681 1.7699749582454634 5533.0
 2    3.029856103443621 1.0036195386474975 5533.0
 3   1.7001119717226236 1.8355512167088455 5533.0
 4    6.175285771098892  3.506179082717531 5533.0
 ..                 ...                ...    ...
 303  5.538901428150571  0.603269532473904 5533.0
 304  4.734420268850179 2.2855305536817214 5533.0
 305  4.886394806219264 1.4407932726596282 5533.0
 306  4.009785460621678 1.0175817209206308 5533.0
 307 1.1319454168715446 0.7414388414619543 5533.0

 [308 rows x 6 columns],
 'cbc_bbh50':                   time                 ra                 dec  \
 0   1401545336.1033118 2.2973503765332497  1.1443092653716405
 1    1401545528.868447 0.7013835134660596 -0.8271197890080897
 2    1401559183.038509  2.899648310383399 -0.1133392113398684
 3   1401560763.5614123 2.6717120149656552  0.9005199779986734
 4   1401580497.2945201  6.271430839414931  0.6550551463909544
 ..                 ...                ...                 ...
 319 1403930554.3866394  5.787327627505722 -1.0234005921124607
 320 1403937302.8449917  5.961292451700461  0.2506938639087098
 321 1403938421.8092914  4.063350832336935  0.6159668542556928
 322 1403948751.8266387  0.560841079792417  1.1028863172524837
 323 1403953029.5559154  5.578382131666027 0.17399237939957274

                    pol          amplitude   seed
 0   1.9809530812521576 0.9100192293000552 5533.0
 1    4.087617600843705 0.8511414058825256 5533.0
 2   0.9426497466563056  1.951975864356356 5533.0
 3   0.2173872038153898 2.5868472746923628 5533.0
 4   1.0720393373489787  2.636235052908976 5533.0
 ..                 ...                ...    ...
 319 1.7613773954057543 1.0064799469043422 5533.0
 320   5.12857821356546 1.1225697253753681 5533.0
 321  2.037373837561321 0.6340927207088773 5533.0
 322  2.593434271900538 1.2655171304003365 5533.0
 323 0.6284298138919641 1.4132356953958098 5533.0

 [324 rows x 6 columns],
 'cbc_ebbh_m100q100e19':                   time                 ra                  dec  \
 0    1401548727.346695 0.9147077431806885   0.8033965393679012
 1   1401550174.9867063 5.5906336460015655  -0.3261980569854155
 2   1401561476.7207022 3.5664338022827438   0.6623659169641704
 3   1401564826.3653522  3.385807396400899  -0.8303796407267332
 4    1401569240.439994 2.7269970107662025 0.054189328486890544
 ..                 ...                ...                  ...
 337 1403917397.2926135 2.5486633508653593   1.4063181270634197
 338 1403920357.5177069 1.4370536004150936   0.5417882395143224
 339  1403943873.719486 1.7700795229007051  0.23103422777203705
 340 1403947828.3760765  2.853488062199355   0.7161010601042709
 341 1403952096.6618042 1.7559917165940342  -0.8175243705410585

                    pol          amplitude   seed
 0    5.978155182777465  5.218246716823333 5533.0
 1   3.7179016414435124 1.0007867329591957 5533.0
 2   1.8348482986970218 3.5953289633012337 5533.0
 3    4.604271933809622   4.92620095808769 5533.0
 4   3.1909105742560646  5.063356628042046 5533.0
 ..                 ...                ...    ...
 337  4.989946568811324  3.125009056035821 5533.0
 338 1.4738648625090573  5.434232370367374 5533.0
 339  2.801834107861366  2.508864161868677 5533.0
 340  5.647934373290486 0.9180881717064989 5533.0
 341  3.583665206596443  4.741318398374387 5533.0

 [342 rows x 6 columns],
 'cbc_ebbh_m100q50e88':                   time                  ra                  dec  \
 0   1401548928.3217034  5.3901990625017655   -0.117967243345528
 1    1401550611.705453  3.8121586957719815  -1.0980009421942105
 2   1401576292.9636846   6.006202608377963  -0.2527659457043814
 3   1401587720.9298427  1.9546764064951447   0.7151401013799705
 4    1401590902.293328  2.0952009947234873   0.4353349916067677
 ..                 ...                 ...                  ...
 324 1403897768.5068605  1.8765376094513433  0.41209405793235154
 325 1403899883.1331773 0.13568086974469962  -0.7520367114375082
 326 1403911338.6921175  2.7688650675827837  0.17288068997160447
 327 1403911448.5238533   5.803445191655173 -0.15481856940340255
 328 1403950903.4018097   5.871599393041337  -0.6915995860784565

                    pol           amplitude   seed
 0   2.5172404281791025  0.5720455627821828 5533.0
 1       5.556767230346  0.6244628047439877 5533.0
 2    0.525174957554286  1.8376295883600238 5533.0
 3   1.6879822923798284 0.33059168425069063 5533.0
 4    3.743081875306246  0.8975405493392373 5533.0
 ..                 ...                 ...    ...
 324  3.693142846868956  0.4769339906133199 5533.0
 325 6.0735058663460935  0.8958920436356692 5533.0
 326  6.175521811884941 0.38612657884772233 5533.0
 327  2.716885781271814  0.9744925609626235 5533.0
 328 0.3273861795546406 0.44408218070163114 5533.0

 [329 rows x 6 columns],
 'cbc_ebbh_m150q100e59':                   time                 ra                 dec  \
 0   1401557596.1155055 3.4373088470395934 0.12280352121833875
 1   1401567000.5123744 6.1604597627058855 -0.7670748514271086
 2   1401568436.6608648  3.690055599710523  0.9974955873719121
 3   1401586766.9513013  4.363209277732532 0.27554214398516125
 4    1401597471.553769  6.282055587581107 -0.8496762687439133
 ..                 ...                ...                 ...
 310 1403932456.9758506  2.171227883290827 -0.7433042793911564
 311  1403942679.031283  3.051705141622871  0.7550980803830947
 312   1403944189.60799  2.966497928971909  0.3126998240242115
 313  1403950115.786318  1.743085508107352  1.1077173421916393
 314 1403958619.2404668  4.376131514985162  0.6351116267783302

                    pol           amplitude   seed
 0    5.674322866427617  0.2403238811314988 5533.0
 1   1.8309295549611118  0.7919285885459174 5533.0
 2   4.9899782639541055 0.26158477096879956 5533.0
 3   0.9810913928177545   2.018118536448211 5533.0
 4    1.145753104934074 0.42339866359038586 5533.0
 ..                 ...                 ...    ...
 310  6.273129253136849 0.22519118924308065 5533.0
 311 1.9000502288009575  1.7370315979203383 5533.0
 312   4.41834276793486 0.49562637465088305 5533.0
 313  5.974105588841115  0.8505477074523089 5533.0
 314  2.875584192583777  1.7251071114625007 5533.0

 [315 rows x 6 columns],
 'cbc_ebbh_m175q50e51':                   time                 ra                  dec  \
 0   1401559280.0163689  1.355401938388608  -0.7750251806924877
 1   1401560453.8923771  5.557870866478883  -1.2712163644430767
 2   1401577381.8521848 3.3480820256344748  -0.4052417940182791
 3   1401579776.0205345  2.062137405274729  -0.9340329469055015
 4   1401624777.5630453 1.8578357963984298 -0.20745348779261644
 ..                 ...                ...                  ...
 303  1403936422.656247 2.8664765229601348   -0.913725749053934
 304 1403939840.7381508 2.1428612481150067  -0.6982981831785008
 305 1403957317.2770126 0.8238730493804809   0.5140443484328734
 306 1403958018.9834235  4.535731526350058  -0.7739623031055883
 307 1403963295.9337838 2.7316207069343568   1.2878704931040619

                    pol           amplitude   seed
 0    4.278412848938732  2.5119485428892996 5533.0
 1   1.9811544384685946  0.4285514486771252 5533.0
 2    5.349334822412646  1.6593259057071565 5533.0
 3    4.770828218215999  1.0188415873877728 5533.0
 4   2.5594298313871944  0.4327284361639664 5533.0
 ..                 ...                 ...    ...
 303 0.7088374508383615  0.7459956671778586 5533.0
 304  3.162878803723484  1.7104377748542656 5533.0
 305   5.04639620250916  0.5552435046818391 5533.0
 306  5.463708560926043 0.38736643381336083 5533.0
 307 2.2848445879582897  0.8485718773587927 5533.0

 [308 rows x 6 columns],
 'cbc_ebbh_m200q100e70':                   time                  ra                   dec  \
 0   1401545234.2667837  3.5758875443087064    0.7605495699510159
 1   1401545840.6586654   2.821280945165479   -0.3357509244016263
 2   1401546696.4178004 0.38559883237214954    0.5983559663685575
 3   1401548222.9845889   5.805422055305658   0.13907795400754921
 4   1401550819.7348912   3.814574907844962 -0.013876173975239551
 ..                 ...                 ...                   ...
 307  1403926268.268142   4.095495882535121   -0.7520103913584008
 308 1403934799.2195303   2.752542385962228  -0.09852350279387928
 309  1403939327.840889  0.5100792221074969      1.32128913619239
 310   1403945168.12983 0.36086312238059387     0.900053146912304
 311  1403962197.415706 0.40176389646929866    0.9794222355598957

                     pol           amplitude   seed
 0     5.584426972919406  1.3168999719014391 5533.0
 1    1.5498180716011125 0.40290931497646304 5533.0
 2    0.4246937422663424 0.30484359938166433 5533.0
 3    3.3905109991460454  1.5639942220220975 5533.0
 4    3.6283846564911806  1.7006738548953277 5533.0
 ..                  ...                 ...    ...
 307 0.16955684671935806  1.9717656485103878 5533.0
 308 0.01763944655728246  0.3245861644127645 5533.0
 309   4.702330490130861  1.9087099764920148 5533.0
 310  2.8801642250350534  2.0247313171261347 5533.0
 311  2.7644062940447065 0.27018997648832915 5533.0

 [312 rows x 6 columns],
 'cbc_ebbh_m200q50e36':                   time                 ra                  dec  \
 0   1401550499.7968411  4.119229346575231   -0.600951458178274
 1   1401551950.6227808 0.3822791398966813   0.8496035792361971
 2   1401553569.7777314  2.470345596392253  -0.8006205025120298
 3   1401571976.9080694 3.3764989690962266 -0.25737016423577974
 4   1401574259.6909683 2.2563131754948205 -0.12998578640658484
 ..                 ...                ...                  ...
 304 1403951581.1351392  4.314260793179305   0.9189263885859648
 305 1403952486.3104515   5.16012044764657  -0.2512215936321593
 306 1403953716.0014021 0.1918306117641106  -0.1430672915760948
 307 1403956142.5784996 1.9979303547760259 -0.21873773408046981
 308 1403956238.9744232  1.342641996987011  -1.0968598300236378

                     pol          amplitude   seed
 0   0.36688984754278436  2.116440275225772 5533.0
 1     2.519998096536832 3.8679559391572025 5533.0
 2     2.459969579452693 1.5954321118780668 5533.0
 3    2.1768243059320938  8.385697854507024 5533.0
 4    3.2383137535411395  5.109279585485161 5533.0
 ..                  ...                ...    ...
 304   2.322788978662098  6.862136449280149 5533.0
 305  5.3266690312446485  7.121623732007805 5533.0
 306  2.0791742814423975 2.8497862594710806 5533.0
 307    4.07782427962936  7.895098530060928 5533.0
 308   3.645162547469774  5.928546265028135 5533.0

 [309 rows x 6 columns],
 'cbc_ebbh_m20q50e60':                   time                  ra                  dec  \
 0   1401566800.4806962   5.653253404277242  0.37147969218890514
 1   1401579676.6860182  1.8394304046699896 -0.15168276203730927
 2   1401584262.5653157 0.23944651621228064  -0.3514498485181094
 3    1401594264.588299   2.459402397628799  -0.7750671400901699
 4     1401595509.21797  0.5605453931733985   0.5953102389060876
 ..                 ...                 ...                  ...
 330 1403913598.0619702  3.7819429373566615  -0.2815398199816255
 331 1403943157.0934525  1.0625431149525655  -0.5641136489570403
 332 1403946495.6851177   1.891733361406729  0.42053886365617976
 333 1403952921.5045974   5.596402565081968   -0.544051020890677
 334 1403962603.8801286  3.8427116741492107   -1.181469827181551

                     pol           amplitude   seed
 0      3.60238001697578  0.6808748649683669 5533.0
 1   0.41126618755966077 0.26166050467481433 5533.0
 2     4.377277451439336  0.7494834878768062 5533.0
 3   0.22735754855595885  0.2552518000290617 5533.0
 4     5.529448359053111  2.1282987501123203 5533.0
 ..                  ...                 ...    ...
 330   4.953846542588274  0.3869033119804915 5533.0
 331 0.11741920247888653  0.8696335576322297 5533.0
 332   5.476345397878303 0.27365241077501096 5533.0
 333   6.104682093576113  0.2514128075841527 5533.0
 334   3.570324261076816  0.4641915543224776 5533.0

 [335 rows x 6 columns],
 'cbc_ebbh_m60q50e20':                   time                 ra                   dec  \
 0   1401553872.5813096 1.6551009390251552   -1.1392815010980275
 1   1401556919.9232755  4.335200638216339   -0.3647920895993125
 2   1401560550.6086144 1.7936663753646307  -0.40253350789330483
 3    1401575993.118598 1.0452598770708637 -0.023354613730357514
 4    1401579072.530251  2.842375691899999    0.6074486994005748
 ..                 ...                ...                   ...
 302   1403934997.23036 2.6409149432792347    0.6872767071842971
 303 1403939426.5837257  5.510413862923704   0.43263297479890994
 304  1403939621.656308  3.151040213325374   -1.1945696682686466
 305   1403948236.64039   6.06446243099374    0.1278211299556843
 306 1403948547.8981702 5.8733779170013705    0.9053710139106665

                     pol          amplitude   seed
 0    4.6524697400929025 1.4956260581355711 5533.0
 1   0.29018704136109547 0.7255862191941722 5533.0
 2     4.239458831550732 2.3832277691528567 5533.0
 3     4.843897845126674 0.9974131877199299 5533.0
 4     1.718401572138179  2.220486651433801 5533.0
 ..                  ...                ...    ...
 302 0.38102988727160086  2.156230092101485 5533.0
 303    5.03586332928223  3.096589941577647 5533.0
 304  1.0849213661782755  1.282403773802806 5533.0
 305   5.730557349808498 1.0203543053121156 5533.0
 306  2.6472725865926257 0.4150986453593546 5533.0

 [307 rows x 6 columns],
 'cbc_ebbh_m80q100e40':                   time                 ra                 dec  \
 0   1401545931.4640071  2.052089583801271  1.2769026186490933
 1   1401549779.5874016   2.98470225877086 -0.4641882997857995
 2    1401553062.462315  2.100402436345232 -0.4762117371024341
 3   1401553366.7809737 4.8122019199103585 0.34860803159826376
 4   1401555083.1778595 0.3205715133786996 -0.4896159370768908
 ..                 ...                ...                 ...
 317 1403953923.0478976  5.301959754099492 0.31916455452800935
 318 1403954254.1079214  0.481001791282484   0.151635776762557
 319 1403957818.7214289  5.880640478875045 -0.8499445736423267
 320 1403960666.8727841  4.440876204442006 -0.1329608028947154
 321 1403963193.7851796 0.6386150548800897 -0.5404563356301572

                    pol           amplitude   seed
 0     4.88445005547296  0.4574513314944873 5533.0
 1    0.640402822448647  0.2497423239249627 5533.0
 2    3.062606046935238  1.2361279969333783 5533.0
 3    5.726502056867733  0.7148775954680252 5533.0
 4    1.708117000794633  0.2830980722597206 5533.0
 ..                 ...                 ...    ...
 317 3.8938290225095797  0.7002078153612382 5533.0
 318  4.782980637097161  0.6653066686942867 5533.0
 319 3.3451550530567795 0.38964754474066443 5533.0
 320 0.7492979963010771  1.1775785144676019 5533.0
 321 1.2263900687434939  0.3657481945173505 5533.0

 [322 rows x 6 columns],
 'ccsn_and16_s20':                   time                 ra                  dec  \
 0   1401551435.8023355 1.3250475830641653  -1.2985453742006037
 1   1401551841.2871394 1.0187593486258775   0.1683919047208067
 2   1401564284.8796659  4.111602527089369   0.7743110813781044
 3    1401565044.742917 0.7442553215995225  0.10500349741327163
 4   1401567092.7846425 0.5855351944319306  0.19143084445476774
 ..                 ...                ...                  ...
 300 1403912766.6368022  3.160592489218133 -0.10192345409299586
 301 1403914389.5412571  4.199119612114964  0.43023644995578186
 302 1403922916.0242126 5.7653197595545125   1.0447830196622871
 303  1403927641.057129  2.377231985831519  0.05089306843665761
 304 1403962907.2191608 1.4254369817231372  -0.2947374346957247

                     pol          amplitude   seed
 0    1.8317904535033396 2.6468692085385293 5533.0
 1    2.9399220066547156 2.9150769224701554 5533.0
 2    3.7842796967177077  1.001719133702402 5533.0
 3     3.782665744968235 1.0475100205042809 5533.0
 4   0.42871306083176036 0.7798758496468348 5533.0
 ..                  ...                ...    ...
 300   1.077537047526341 0.5127426607837938 5533.0
 301   4.800537273894688 2.6585135366847137 5533.0
 302   4.510574172662423 0.6097721406334826 5533.0
 303   5.715500661357712 1.7375095353947745 5533.0

As you can see, each injection type has different parameters, i.e. dataframes with different sizes/keys. The same for the other two:

In [55]:
inj_attributes

{'cbc_bbh10': {'hrss_norm': np.float64(1e-22),
  'sampling_rate': np.float64(16384.0),
  'type': 'WAVE'},
 'cbc_bbh125': {'hrss_norm': np.float64(1e-22),
  'sampling_rate': np.float64(16384.0),
  'type': 'WAVE'},
 'cbc_bbh35': {'hrss_norm': np.float64(1e-22),
  'sampling_rate': np.float64(16384.0),
  'type': 'WAVE'},
 'cbc_bbh50': {'hrss_norm': np.float64(1e-22),
  'sampling_rate': np.float64(16384.0),
  'type': 'WAVE'},
 'cbc_ebbh_m100q100e19': {'hrss_norm': np.float64(1e-22),
  'sampling_rate': np.float64(16384.0),
  'type': 'WAVE'},
 'cbc_ebbh_m100q50e88': {'hrss_norm': np.float64(1e-22),
  'sampling_rate': np.float64(16384.0),
  'type': 'WAVE'},
 'cbc_ebbh_m150q100e59': {'hrss_norm': np.float64(1e-22),
  'sampling_rate': np.float64(16384.0),
  'type': 'WAVE'},
 'cbc_ebbh_m175q50e51': {'hrss_norm': np.float64(1e-22),
  'sampling_rate': np.float64(16384.0),
  'type': 'WAVE'},
 'cbc_ebbh_m200q100e70': {'hrss_norm': np.float64(1e-22),
  'sampling_rate': np.float64(16384.0),
  'type': 'WAVE'},
 'cbc_ebbh_m200q50e36': {'hrss_norm': np.float64(1e-22),
  'sampling_rate': np.float64(16384.0),
  'type': 'WAVE'},
 'cbc_ebbh_m20q50e60': {'hrss_norm': np.float64(1e-22),
  'sampling_rate': np.float64(16384.0),
  'type': 'WAVE'},
 'cbc_ebbh_m60q50e20': {'hrss_norm': np.float64(1e-22),
  'sampling_rate': np.float64(16384.0),
  'type': 'WAVE'},
 'cbc_ebbh_m80q100e40': {'hrss_norm': np.float64(1e-22),
  'sampling_rate': np.float64(16384.0),
  'type': 'WAVE'},
 'ccsn_and16_s20': {'hrss_norm': np.float64(1e-22),
  'sampling_rate': np.float64(1994.0577080300968),
  'type': 'WAVE'},
 'ccsn_and16_s20s': {'hrss_norm': np.float64(1e-22),
  'sampling_rate': np.float64(1991.2385503783028),
  'type': 'WAVE'},
 'ccsn_and19_s15fr': {'hrss_norm': np.float64(1e-22),
  'sampling_rate': np.float64(1984.0876173091835),
  'type': 'WAVE'},
 'ccsn_mez23_d15': {'hrss_norm': np.float64(1e-22),
  'sampling_rate': np.float64(16382.64751526837),
  'type': 'WAVE'},
 'ccsn_mez23_d9': {'hrss_norm': np.float64(1e-22),
  'sampling_rate': np.float64(16382.485487156586),
  'type': 'WAVE'},
 'ccsn_mor18_m13': {'hrss_norm': np.float64(1e-22),
  'sampling_rate': np.float64(20376.770563067446),
  'type': 'WAVE'},
 'ccsn_oco18_mesa20pertlr': {'hrss_norm': np.float64(1e-22),
  'sampling_rate': np.float64(16382.012615217667),
  'type': 'WAVE'},
 'ccsn_pan18_s402d-dd2': {'hrss_norm': np.float64(1e-22),
  'sampling_rate': np.float64(2750.5776213001664),
  'type': 'WAVE'},
 'ccsn_pan21_s40fr': {'hrss_norm': np.float64(1e-22),
  'sampling_rate': np.float64(497.12660820457177),
  'type': 'WAVE'},
 'ccsn_pow18_s18': {'hrss_norm': np.float64(1e-22),
  'sampling_rate': np.float64(60810.45634305277),
  'type': 'WAVE'},
 'ccsn_pow20_y20': {'hrss_norm': np.float64(1e-22),
  'sampling_rate': np.float64(11413.103542816167),
  'type': 'WAVE'},
 'ccsn_pow21_z100': {'hrss_norm': np.float64(1e-22),
  'sampling_rate': np.float64(16382.354854910775),
  'type': 'WAVE'},
 'ccsn_pow23_m39-1e12': {'hrss_norm': np.float64(1e-22),
  'sampling_rate': np.float64(601588.4341066766),
  'type': 'WAVE'},
 'ccsn_rad19_s10': {'hrss_norm': np.float64(1e-22),
  'sampling_rate': np.float64(96153.84615416058),
  'type': 'WAVE'},
 'che_1': {'hrss_norm': np.float64(1e-22),
  'sampling_rate': np.float64(16384.0),
  'type': 'WAVE'},
 'che_2': {'hrss_norm': np.float64(1e-22),
  'sampling_rate': np.float64(16384.0),
  'type': 'WAVE'},
 'che_3': {'hrss_norm': np.float64(1e-22),
  'sampling_rate': np.float64(16384.0),
  'type': 'WAVE'},
 'cs_cusp': {'type': 'CSC'},
 'cs_kink': {'type': 'CSK'},
 'cs_kinkkink': {'type': 'CSKK'},
 'ga_1': {'type': 'GA'},
 'ga_100': {'type': 'GA'},
 'ga_20': {'type': 'GA'},
 'ga_3': {'type': 'GA'},
 'proca_w85': {'hrss_norm': np.float64(1e-22),
  'sampling_rate': np.float64(948509.4850947846),
  'type': 'WAVE'},
 'sg_1304q9': {'type': 'SG'},
 'sg_14q100': {'type': 'SG'},
 'sg_1615q100': {'type': 'SG'},
 'sg_196q700': {'type': 'SG'},
 'sg_2000q3': {'type': 'SG'},
 'sg_235q100': {'type': 'SG'},
 'sg_235q3': {'type': 'SG'},
 'sg_235q9': {'type': 'SG'},
 'sg_2477q9': {'type': 'SG'},
 'sg_25q9': {'type': 'SG'},
 'sg_2634q700': {'type': 'SG'},
 'sg_3067q3': {'type': 'SG'},
 'sg_32q3': {'type': 'SG'},
 'sg_40q700': {'type': 'SG'},
 'sg_554q9': {'type': 'SG'},
 'sg_612q700': {'type': 'SG'},
 'sg_70q100': {'type': 'SG'},
 'sg_70q3': {'type': 'SG'},
 'sg_70q9': {'type': 'SG'},
 'sg_849q3': {'type': 'SG'},
 'wnb_100_120_t1000': {'type': 'WNB'},
 'wnb_100_200_t100': {'type': 'WNB'},
 'wnb_1220_1520_t500': {'type': 'WNB'},
 'wnb_1395_1405_t100': {'type': 'WNB'},
 'wnb_1600_1700_t2000': {'type': 'WNB'},
 'wnb_250_350_t100': {'type': 'WNB'},
 'wnb_250_350_t800': {'type': 'WNB'},
 'wnb_295_305_t400': {'type': 'WNB'},
 'wnb_30_50_t1800': {'type': 'WNB'},
 'wnb_400_450_t300': {'type': 'WNB'},
 'wnb_400_500_t30': {'type': 'WNB'},
 'wnb_55_65_t500': {'type': 'WNB'},
 'wnb_750_850_t100': {'type': 'WNB'},
 'wnb_800_1000_t10': {'type': 'WNB'},
 'wnb_80_90_t200': {'type': 'WNB'},
 'wnb_995_1005_t1000': {'type': 'WNB'}}

In [56]:
inj_STRAIN_time_series

{'cbc_bbh10':                        hcross                  hplus              times
 0      -1.139692032266351e-24 -1.536460582205865e-23  -22.0752505379375
 1      -1.198607722349395e-24 -1.536013235410152e-23 -22.07518950278125
 2      -1.257505919654757e-24  -1.53554329734781e-23   -22.075128467625
 3       -1.31638576599636e-24 -1.535050774360941e-23 -22.07506743246875
 4      -1.375246392458546e-24 -1.534535674030533e-23  -22.0750063973125
 ...                       ...                    ...                ...
 363798                    0.0                   -0.0 0.1292172355000005
 363799                    0.0                   -0.0 0.1292782706562505
 363800                    0.0                   -0.0 0.1293393058125005
 363801                    0.0                   -0.0 0.1294003409687505
 363802                    0.0                   -0.0 0.1294613761250005

 [363803 rows x 3 columns],
 'cbc_bbh125':                      hcross                  hplus             times
 0     2.415735850416778e-22  1.346098112206854e-22  -0.0460205078125
 1     2.419119100312408e-22  1.340086374837242e-22 -0.04595947265625
 2     2.422487840161079e-22  1.334064681801457e-22     -0.0458984375
 3     2.425842037533694e-22  1.328033066460533e-22 -0.04583740234375
 4     2.429181660069641e-22  1.321991562284579e-22  -0.0457763671875
 ...                     ...                    ...               ...
 33945 1.154926687588049e-26 -4.073621858212475e-27  2.02581787109375
 33946 1.154927996631586e-26 -4.073519443521208e-27     2.02587890625
 33947 1.154929295766943e-26 -4.073417053059075e-27  2.02593994140625
 33948 1.154930587793702e-26 -4.073314679752676e-27   2.0260009765625
 33949 1.154931875511331e-26 -4.073212316527205e-27  2.02606201171875

 [33950 rows x 3 columns],
 'cbc_bbh35':                       hcross                  hplus              times
 0     -1.765107910831989e-23 -6.594172980673536e-23   -1.1395263671875
 1     -1.790420532168529e-23 -6.587430992567813e-23  -1.13946533203125
 2     -1.815707827069288e-23 -6.580591718910376e-23    -1.139404296875
 3     -1.840969496564998e-23 -6.573655234656867e-23  -1.13934326171875
 4     -1.866205153480377e-23 -6.566621637570022e-23   -1.1392822265625
 ...                      ...                    ...                ...
 24279                    0.0                   -0.0 0.3423461914062499
 24280                    0.0                   -0.0 0.3424072265624999
 24281                    0.0                   -0.0 0.3424682617187499
 24282                    0.0                   -0.0 0.3425292968749999
 24283                    0.0                   -0.0 0.3425903320312499

 [24284 rows x 3 columns],
 'cbc_bbh50':                      hcross                  hplus              times
 0     5.226197798245598e-23  9.432403985057212e-23    -0.418701171875
 1     5.260694156279369e-23  9.413627406176904e-23  -0.41864013671875
 2     5.295124781764518e-23  9.394723771554453e-23   -0.4185791015625
 3     5.329489203982557e-23  9.375693304383232e-23  -0.41851806640625
 4     5.363786952944025e-23  9.356536229607354e-23     -0.41845703125
 ...                     ...                    ...                ...
 12038 1.064530305431075e-26   -3.7575990486359e-27 0.3160400390625001
 12039 1.064543134858452e-26 -3.756960407342788e-27 0.3161010742187501
 12040 1.064554637244281e-26 -3.756325287862646e-27 0.3161621093750001
 12041 1.064564633158262e-26 -3.755694020362004e-27 0.3162231445312501
 12042  1.06457325949038e-26 -3.755066180637383e-27 0.3162841796875001

 [12043 rows x 3 columns],
 'cbc_ebbh_m100q100e19':                       hcross                 hplus              times
 0                       -0.0                   0.0       -5.780525034
 1                        0.0                   0.0  -5.78046399884375
 2     -6.399315627125431e-78 2.136809886971208e-77   -5.7804029636875
 3     -4.504849244245491e-54 1.504224352306667e-53  -5.78034192853125
 4     -4.678411290818845e-46 1.562178845994873e-45    -5.780280893375
 ...                      ...                   ...                ...
 99478 -8.800345947570378e-35 2.938543326372054e-34 0.2911302394374999
 99479  -6.96789170004002e-35 2.326664403424815e-34 0.2911912745937499
 99480 -5.135223329622707e-35 1.714713982222368e-34 0.2912523097499999
 99481 -3.302397159441921e-35 1.102710869745666e-34 0.2913133449062499
 99482 -1.469469512624026e-35 4.906738729766272e-35 0.2913743800624999

 [99483 rows x 3 columns],
 'cbc_ebbh_m100q50e88':                      hcross                  hplus             times
 0                      -0.0                    0.0      -0.073882359
 1                       0.0                    0.0 -0.07382132384375
 2     7.574610641813467e-72 -6.308475667602303e-71  -0.0737602886875
 3     4.924842606520835e-51 -4.101629934415335e-50 -0.07369925353125
 4     5.046254690726054e-44 -4.202747366739891e-43   -0.073638218375
 ...                     ...                    ...               ...
 4482 -2.132514182335953e-32  1.776053511691499e-31   0.1996772113125
 4483 -1.695688422800543e-32  1.412245415761119e-31  0.19973824646875
 4484 -1.258605799807197e-32  1.048223392415735e-31    0.199799281625
 4485 -8.213325552903928e-33   6.84042610911109e-32  0.19986031678125
 4486 -3.839349311847435e-33  3.197582405031216e-32   0.1999213519375

 [4487 rows x 3 columns],
 'cbc_ebbh_m150q100e59':                       hcross                  hplus             times
 0                        0.0                    0.0      -0.161309328
 1     -1.198622360181299e-71  5.678789631871021e-71 -0.16124829284375
 2     -6.249157237912841e-51  2.960703096279819e-50  -0.1611872576875
 3     -6.024157467564352e-44  2.854103519509355e-43 -0.16112622253125
 4     -2.044631484535894e-40  9.686981038483354e-40   -0.161065187375
 ...                      ...                    ...               ...
 10357  3.437013268692991e-35 -1.628375705581294e-34  0.47083178528125
 10358  2.713658682934154e-35 -1.285667388246682e-34   0.4708928204375
 10359  1.990226213872994e-35 -9.429221716430071e-35  0.47095385559375
 10360  1.266736626141882e-35 -6.001498935626327e-35     0.47101489075
 10361   5.43210684377661e-36 -2.573603918000421e-35  0.47107592590625

 [10362 rows x 3 columns],
 'cbc_ebbh_m175q50e51':                      hcross                  hplus             times
 0                      -0.0                    0.0      -0.486433003
 1                       0.0                    0.0 -0.48637196784375
 2     3.840203705166277e-66 -1.585492895086574e-65  -0.4863109326875
 3     2.258141671129422e-48 -9.323118903451591e-48 -0.48624989753125
 4     2.216700597834159e-42 -9.152022440036059e-42   -0.486188862375
 ...                     ...                    ...               ...
 13496 4.486114654186506e-35 -1.852168128787077e-34     0.33729746575
 13497 3.584626495532722e-35 -1.479973531758824e-34  0.33735850090625
 13498 2.683080257723398e-35 -1.107754955771241e-34   0.3374195360625
 13499 1.781490548688429e-35 -7.355184319546673e-35  0.33748057121875
 13500  8.79871976355038e-36 -3.632699914383299e-35    0.337541606375

 [13501 rows x 3 columns],
 'cbc_ebbh_m200q100e70':                      hcross                 hplus             times
 0                       0.0                   0.0      -0.181914156
 1     -5.10517345631264e-75 2.821219084558696e-74 -0.18185312084375
 2    -8.804634639998376e-53  4.86561396816321e-52  -0.1817920856875
 3    -2.722033568382951e-45 1.504249193029105e-44 -0.18173105053125
 4    -1.653021525981545e-41 9.134921499130218e-41   -0.181670015375
 ...                     ...                   ...               ...
 8969 -1.096311486493733e-34  6.05843251906053e-34  0.36551016040625
 8970 -8.642928357270378e-35 4.776251901461455e-34   0.3655711955625
 8971 -6.322414634471797e-35 3.493890458356253e-34  0.36563223071875
 8972 -4.001661559282912e-35 2.211396744420833e-34    0.365693265875
 8973 -1.680756994444701e-35   9.2881931433092e-35  0.36575430103125

 [8974 rows x 3 columns],
 'cbc_ebbh_m200q50e36':                       hcross                  hplus              times
 0                        0.0                    0.0       -3.631728462
 1      1.041848498090892e-57 -3.750602887656627e-57  -3.63166742684375
 2      1.372416263771422e-44 -4.940630438494856e-44   -3.6316063916875
 3      3.898099272639808e-40 -1.403296392433784e-39  -3.63154535653125
 4      7.203529173361915e-38 -2.593234752311642e-37    -3.631484321375
 ...                      ...                    ...                ...
 65642 -4.458349511410172e-34  1.604983697949135e-33 0.3747412645625001
 65643 -3.381926611307299e-34  1.217476796046823e-33 0.3748022997187501
 65644 -2.305370036572673e-34  8.299217719404886e-34 0.3748633348750001
 65645 -1.228722342543362e-34  4.423339453402796e-34 0.3749243700312501
 65646  -1.52026084556721e-35  5.472863595644776e-35 0.3749854051875001

 [65647 rows x 3 columns],
 'cbc_ebbh_m20q50e60':                      hcross                  hplus             times
 0     5.054899119471564e-24  6.562992915384289e-23  -0.1488037109375
 1     5.554350126112393e-24  6.559006159270579e-23 -0.14874267578125
 2     6.053534166088352e-24   6.55465939831295e-23   -0.148681640625
 3     6.552475505911747e-24   6.54997281423034e-23 -0.14862060546875
 4     7.051199901124057e-24  6.544964338178394e-23  -0.1485595703125
 ...                     ...                    ...               ...
 2845  1.585883263442124e-31 -5.043589539754954e-31  0.02484130859375
 2846 -9.515239198662479e-33 -5.010024072223511e-31     0.02490234375
 2847 -1.595574926100283e-31 -4.473209511906947e-31  0.02496337890625
 2848 -2.781925754360571e-31 -3.538480696018006e-31   0.0250244140625
 2849 -3.566553015892203e-31 -2.341255062950773e-31  0.02508544921875

 [2850 rows x 3 columns],
 'cbc_ebbh_m60q50e20':                       hcross                 hplus             times
 0      1.147842709774789e-23 6.671317227591584e-23 -0.66595458984375
 1      1.189038423188199e-23 6.664097850956748e-23  -0.6658935546875
 2      1.230189984962505e-23 6.656627297442329e-23 -0.66583251953125
 3      1.271297143592878e-23 6.648909027638522e-23   -0.665771484375
 4      1.312359728039684e-23  6.64094647971716e-23 -0.66571044921875
 ...                      ...                   ...               ...
 12140 -1.432662424695511e-31 1.699870567453438e-31  0.07501220703125
 12141 -1.219289837745227e-31 1.811529103576847e-31   0.0750732421875
 12142 -9.991297414868821e-32 1.898037612240255e-31  0.07513427734375
 12143 -7.750233617907185e-32  1.95934694685974e-31      0.0751953125
 12144 -5.496681381105417e-32 1.995509842671657e-31  0.07525634765625

 [12145 rows x 3 columns],
 'cbc_ebbh_m80q100e40':                      hcross                  hplus             times
 0     2.552033452964561e-23  1.219031873825115e-22 -0.08990478515625
 1     2.631218048839687e-23  1.217347504646973e-22       -0.08984375
 2     2.710296134285254e-23  1.215612687757331e-22 -0.08978271484375
 3     2.789269257782836e-23  1.213828471978112e-22  -0.0897216796875
 4     2.868139227143143e-23  1.211995895752799e-22 -0.08966064453125
 ...                     ...                    ...               ...
 3111  -4.54547652382506e-31 -9.525056250427297e-32   0.0999755859375
 3112 -4.549827484551622e-31 -5.522884552060638e-32  0.10003662109375
 3113 -4.520430314330206e-31 -1.584155514554856e-32     0.10009765625
 3114 -4.458190096430471e-31  2.263835114653459e-32  0.10015869140625
 3115  -4.36412501952643e-31  5.994365863971408e-32   0.1002197265625

 [3116 rows x 3 columns],
 'ccsn_and16_s20':                     hcross                  hplus       times
 0   -3.107330342789669e-24 -3.356187495824608e-23 -0.22450525
 1   -3.683088451208437e-24 -2.964794283669769e-23 -0.22400376
 2   -4.129269971313828e-24 -2.579472318378694e-23 -0.22350173
 3   -4.487602954387813e-24 -2.196911268701173e-23 -0.22299773
 4   -4.716994963534731e-24 -1.828297141513582e-23 -0.22249373
 ..                     ...                    ...         ...
 804  2.395399375926976e-24  2.487112200732029e-23     0.18835
 805  1.405873964950662e-23  3.681148893028821e-23     0.18885
 806   4.95352309236258e-23   2.71816451562906e-23    0.189351
 807 -1.265456310133041e-24  1.707363173388788e-23    0.189851
 808  9.321739847626944e-23 -1.455373122802495e-23    0.190352

 [809 rows x 3 columns],
 'ccsn_and16_s20s':                     hcross                  hplus      times
 0    6.177479814274575e-23 -3.160566818255249e-23 -0.3996735
 1    5.368229278674948e-23 -2.279604693914702e-23 -0.3991713
 2    5.033555924865992e-23 -2.414186625546722e-23 -0.3986666
 3    4.223496184176995e-23 -1.548694054936737e-23 -0.3981646
 4    3.900800590012326e-23 -1.710967104878908e-23 -0.3976608
 ..                     ...                    ...        ...
 987  -5.38738648154953e-23  5.571578738514529e-23   0.119593
 988  -1.31072032366925e-23 -8.777041476289109e-23   0.119667
 989 -1.881387979948522e-23 -6.044632825850152e-23   0.119729
 990 -1.905292517368389e-23  5.134665699065285e-23   0.119779
 991  -2.39488682470699e-24   1.58255565995607e-22   0.119825

 [992 rows x 3 columns],
 'ccsn_and19_s15fr':                     hcross                  hplus       times
 0    1.131174062531217e-22  -2.42222736815029e-23 -0.18382893
 1    2.117971722639174e-23 -1.735609626893554e-23 -0.18332492
 2    1.101819643185059e-22 -2.238639883721807e-23 -0.18282383
 3     2.70989749133543e-22 -1.601498986696763e-23 -0.18232198
 4    2.201312118526137e-23 -2.082538551794169e-23 -0.18182112
 ..                     ...                    ...         ...
 969  7.928884826316694e-23  9.833910726478466e-23   0.2640718
 970  1.055047709734171e-23  1.065147161263059e-23  0.26457208
 971 -3.134589584733484e-23  3.818791825990745e-23  0.26507224
 972 -6.923704562131919e-23   8.46167604763107e-23  0.26557137
 973 -2.677634080641929e-23  2.887513574636397e-23  0.26607163

 [974 rows x 3 columns],
 'ccsn_mez23_d15':                       hcross                  hplus               times
 0      5.920195537097329e-24  5.920195537097329e-24 -0.3617852361454378
 1      6.156734605078561e-24  6.156734605078561e-24 -0.3617241959503736
 2       6.28808146678545e-24   6.28808146678545e-24 -0.3616631557553094
 3      6.348183530797266e-24  6.348183530797266e-24 -0.3616021155602452
 4      6.343227843098564e-24  6.343227843098564e-24  -0.361541075365181
 ...                      ...                    ...                 ...
 12109 -5.552083705767646e-23 -5.552083705767646e-23  0.3773504858868055
 12110 -9.187159943687884e-23 -9.187159943687884e-23  0.3774115260818697
 12111 -1.071395212910851e-22 -1.071395212910851e-22  0.3774725662769339
 12112 -9.415012687142309e-23 -9.415012687142309e-23  0.3775336064719981
 12113 -4.579224091305986e-23 -4.579224091305986e-23  0.3775946466670622

 [12114 rows x 3 columns],
 'ccsn_mez23_d9':                       hcross                  hplus               times
 0      8.749686206379449e-25 -1.386743516980438e-24 -0.2087595317989045
 1      7.499906274843593e-25 -1.278181478291429e-24 -0.2086984910001329
 2      6.609955731031936e-25 -1.178037214253179e-24 -0.2086374502013613
 3      5.487994631058702e-25  -1.06846092097478e-24 -0.2085764094025897
 4      4.721111386921024e-25 -9.673535501065585e-25 -0.2085153686038181
 ...                      ...                    ...                 ...
 10813 -2.207103140548496e-23 -8.165787288759408e-23  0.4512746253185091
 10814  3.187312920856158e-23 -8.874939613033798e-23  0.4513356661172807
 10815  8.341742897875314e-23 -8.554276498147396e-23  0.4513967069160524
 10816  1.258857870352822e-22 -7.209312655175974e-23  0.4514577477148239
 10817  1.525679816483332e-22 -4.842020565922803e-23  0.4515187885135955

 [10818 rows x 3 columns],
 'ccsn_mor18_m13':        hcross                  hplus              times
 0         0.0 -1.239154648264713e-23      -0.4813473709
 1         0.0 -1.226848771909312e-23     -0.48129829541
 2         0.0 -1.214520729159959e-23     -0.48124600018
 3         0.0 -1.202170808611689e-23     -0.48119139307
 4         0.0 -1.189799699792388e-23     -0.48114528058
 ...       ...                    ...                ...
 24986     0.0  3.876873942245173e-23      0.76794991505
 24987     0.0  1.742477096362917e-23      0.76799949755
 24988     0.0 -2.656409388329456e-24 0.7680499111499999
 24989     0.0 -1.340285347783219e-23      0.76809967755
 24990     0.0 -1.038035960220835e-23      0.76815021005

 [24991 rows x 3 columns],
 'ccsn_oco18_mesa20pertlr':                      hcross                  hplus               times
 0    -6.721383065688824e-26 -9.509595235410102e-24 -0.2058355147928546
 1    -6.269828953502924e-26  -9.45956193767927e-24 -0.2057744722321212
 2    -2.157469238627137e-26 -9.381702603061649e-24 -0.2057134296713879
 3    -1.598744030404659e-26 -9.322054684668618e-24 -0.2056523871106545
 4    -1.949908723752209e-26 -9.260604856743843e-24 -0.2055913445499212
 ...                     ...                    ...                 ...
 8239 -1.214067645296635e-22  2.403988758071979e-22  0.2970941430892121
 8240 -5.520399026245096e-23  2.383913819856329e-22  0.2971551856499455
 8241  2.902648727019888e-23  1.865672513311759e-22  0.2972162282106787
 8242  1.093536545666993e-22  1.143711979595339e-22  0.2972772707714121
 8243  1.495330509403321e-22  4.020409111583667e-23  0.2973383133321454

 [8244 rows x 3 columns],
 'ccsn_pan18_s402d-dd2':         hcross                  hplus               times
 0          0.0  4.969701558625083e-24         -1.62768355
 1          0.0  4.778207703595081e-24         -1.62731999
 2          0.0  4.588414975946098e-24         -1.62644986
 3          0.0  4.401799553001536e-24         -1.62558143
 4          0.0  4.217669491357347e-24         -1.62471445
 ...        ...                    ...                 ...
 260678     0.0  -8.08925296153807e-25 0.03929499999999986
 260679     0.0 -4.509004498888462e-24 0.03929999999999989
 260680     0.0  -7.56846964312062e-24 0.03930499999999992
 260681     0.0  4.599167722605537e-24 0.03930999999999996
 260682     0.0 -1.277817702335398e-23 0.03931499999999999

 [260683 rows x 3 columns],
 'ccsn_pan21_s40fr':                      hcross                  hplus       times
 0     1.824508822255179e-31 -1.818927778673026e-25  -0.6835373
 1     1.515324866558646e-31 -1.816724871432247e-25 -0.68152574
 2     1.119217704847964e-31 -1.812649713319801e-25 -0.67979692
 3     1.079832264752963e-31 -1.810085928428862e-25 -0.67806956
 4     1.066119223216015e-31 -1.807506144036192e-25 -0.67634783
 ...                     ...                    ...         ...
 46496 5.031578645703403e-25  5.331676507554464e-24     0.26001
 46497 4.907118444444022e-25   5.22320514169181e-24     0.26002
 46498  4.81786402600613e-25   5.08506335685299e-24     0.26003
 46499                  -0.0                    0.0     0.26004
 46500 4.782928147822542e-25   4.85236552158233e-24     0.26005

 [46501 rows x 3 columns],
 'ccsn_pow18_s18':                       hcross                  hplus               times
 0     -1.456909175169374e-22  1.008273904518194e-22 -0.3883822510180001
 1      -3.13634470907468e-22  2.602536558910304e-22    -0.3883658064777
 2     -3.122397048867307e-22  2.595708956439507e-22 -0.3883458064777001
 3      -2.55617575273684e-22  2.064631888491073e-22    -0.3883258064777
 4     -2.553397416675638e-22   2.06018188103625e-22    -0.3883058064777
 ...                      ...                    ...                 ...
 41390  2.023772398466835e-22 -2.538585439276581e-22  0.4397288471137999
 41391  2.138101821950815e-22 -2.583796807263017e-22  0.4397488471137999
 41392  2.816855872897041e-22 -3.155424948102217e-22     0.4397688471138
 41393  2.882183889082504e-22 -3.152797883765822e-22  0.4397888471137999

Let's check on the keys

In [57]:
print("inj_parameters", inj_parameters.keys())
print(" each having different attributes, example ", list(inj_parameters['cbc_bbh10'].keys()))
print()
print("inj_attributes", inj_attributes.keys())
print(" each having different attributes, example ", list(inj_attributes['cbc_bbh10'].keys()))
print()
print("inj_STRAIN_time_series", inj_STRAIN_time_series.keys())
print(" each having ", list(inj_STRAIN_time_series['cbc_bbh10'].keys()))

inj_parameters dict_keys(['cbc_bbh10', 'cbc_bbh125', 'cbc_bbh35', 'cbc_bbh50', 'cbc_ebbh_m100q100e19', 'cbc_ebbh_m100q50e88', 'cbc_ebbh_m150q100e59', 'cbc_ebbh_m175q50e51', 'cbc_ebbh_m200q100e70', 'cbc_ebbh_m200q50e36', 'cbc_ebbh_m20q50e60', 'cbc_ebbh_m60q50e20', 'cbc_ebbh_m80q100e40', 'ccsn_and16_s20', 'ccsn_and16_s20s', 'ccsn_and19_s15fr', 'ccsn_mez23_d15', 'ccsn_mez23_d9', 'ccsn_mor18_m13', 'ccsn_oco18_mesa20pertlr', 'ccsn_pan18_s402d-dd2', 'ccsn_pan21_s40fr', 'ccsn_pow18_s18', 'ccsn_pow20_y20', 'ccsn_pow21_z100', 'ccsn_pow23_m39-1e12', 'ccsn_rad19_s10', 'che_1', 'che_2', 'che_3', 'cs_cusp', 'cs_kink', 'cs_kinkkink', 'ga_1', 'ga_100', 'ga_20', 'ga_3', 'proca_w85', 'sg_1304q9', 'sg_14q100', 'sg_1615q100', 'sg_196q700', 'sg_2000q3', 'sg_235q100', 'sg_235q3', 'sg_235q9', 'sg_2477q9', 'sg_25q9', 'sg_2634q700', 'sg_3067q3', 'sg_32q3', 'sg_40q700', 'sg_554q9', 'sg_612q700', 'sg_70q100', 'sg_70q3', 'sg_70q9', 'sg_849q3', 'wnb_100_120_t1000', 'wnb_100_200_t100', 'wnb_1220_1520_t500', 'wnb_1395_1405_t100', 'wnb_1600_1700_t2000', 'wnb_250_350_t100', 'wnb_250_350_t800', 'wnb_295_305_t400', 'wnb_30_50_t1800', 'wnb_400_450_t300', 'wnb_400_500_t30', 'wnb_55_65_t500', 'wnb_750_850_t100', 'wnb_800_1000_t10', 'wnb_80_90_t200', 'wnb_995_1005_t1000'])
 each having different attributes, example  ['time', 'ra', 'dec', 'pol', 'amplitude', 'seed']

inj_attributes dict_keys(['cbc_bbh10', 'cbc_bbh125', 'cbc_bbh35', 'cbc_bbh50', 'cbc_ebbh_m100q100e19', 'cbc_ebbh_m100q50e88', 'cbc_ebbh_m150q100e59', 'cbc_ebbh_m175q50e51', 'cbc_ebbh_m200q100e70', 'cbc_ebbh_m200q50e36', 'cbc_ebbh_m20q50e60', 'cbc_ebbh_m60q50e20', 'cbc_ebbh_m80q100e40', 'ccsn_and16_s20', 'ccsn_and16_s20s', 'ccsn_and19_s15fr', 'ccsn_mez23_d15', 'ccsn_mez23_d9', 'ccsn_mor18_m13', 'ccsn_oco18_mesa20pertlr', 'ccsn_pan18_s402d-dd2', 'ccsn_pan21_s40fr', 'ccsn_pow18_s18', 'ccsn_pow20_y20', 'ccsn_pow21_z100', 'ccsn_pow23_m39-1e12', 'ccsn_rad19_s10', 'che_1', 'che_2', 'che_3', 'cs_cusp', 'cs_kink', 'cs_kinkkink', 'ga_1', 'ga_100', 'ga_20', 'ga_3', 'proca_w85', 'sg_1304q9', 'sg_14q100', 'sg_1615q100', 'sg_196q700', 'sg_2000q3', 'sg_235q100', 'sg_235q3', 'sg_235q9', 'sg_2477q9', 'sg_25q9', 'sg_2634q700', 'sg_3067q3', 'sg_32q3', 'sg_40q700', 'sg_554q9', 'sg_612q700', 'sg_70q100', 'sg_70q3', 'sg_70q9', 'sg_849q3', 'wnb_100_120_t1000', 'wnb_100_200_t100', 'wnb_1220_1520_t500', 'wnb_1395_1405_t100', 'wnb_1600_1700_t2000', 'wnb_250_350_t100', 'wnb_250_350_t800', 'wnb_295_305_t400', 'wnb_30_50_t1800', 'wnb_400_450_t300', 'wnb_400_500_t30', 'wnb_55_65_t500', 'wnb_750_850_t100', 'wnb_800_1000_t10', 'wnb_80_90_t200', 'wnb_995_1005_t1000'])
 each having different attributes, example  ['hrss_norm', 'sampling_rate', 'type']

inj_STRAIN_time_series dict_keys(['cbc_bbh10', 'cbc_bbh125', 'cbc_bbh35', 'cbc_bbh50', 'cbc_ebbh_m100q100e19', 'cbc_ebbh_m100q50e88', 'cbc_ebbh_m150q100e59', 'cbc_ebbh_m175q50e51', 'cbc_ebbh_m200q100e70', 'cbc_ebbh_m200q50e36', 'cbc_ebbh_m20q50e60', 'cbc_ebbh_m60q50e20', 'cbc_ebbh_m80q100e40', 'ccsn_and16_s20', 'ccsn_and16_s20s', 'ccsn_and19_s15fr', 'ccsn_mez23_d15', 'ccsn_mez23_d9', 'ccsn_mor18_m13', 'ccsn_oco18_mesa20pertlr', 'ccsn_pan18_s402d-dd2', 'ccsn_pan21_s40fr', 'ccsn_pow18_s18', 'ccsn_pow20_y20', 'ccsn_pow21_z100', 'ccsn_pow23_m39-1e12', 'ccsn_rad19_s10', 'che_1', 'che_2', 'che_3', 'proca_w85'])
 each having  ['hcross', 'hplus', 'times']

Now let's keep only o4b-0 injections:

In [58]:
# keep only o4b-0 triggers
for inj_wave_type in inj_parameters: # loop over inj_parameters keys
  mask_o4b0 = (inj_parameters[inj_wave_type]["time"] > gpsStart_o4b0) & (inj_parameters[inj_wave_type]["time"] < gpsEnd_o4b0)
  inj_parameters[inj_wave_type] = inj_parameters[inj_wave_type][mask_o4b0]

## How to look for injection information:

Example. I want to get the injection with maximum amplitude of the type `ccsn_pan21_s40fr`:

In [59]:
inj_parameters['ccsn_pan21_s40fr'].loc[inj_parameters['ccsn_pan21_s40fr']['amplitude'].idxmax()]

time         1402360714.3399901
ra           0.6646404911099573
dec         0.34313265791998454
pol          0.3148485673882525
amplitude     37.09340153372006
seed                     5533.0
Name: 100, dtype: float64

where we see the injection of maximum amplitude of the type `ccsn_pan21_s40fr` sits in index 100 of inj_parameters:

In [60]:
inj_parameters['ccsn_pan21_s40fr'].loc[100]

time         1402360714.3399901
ra           0.6646404911099573
dec         0.34313265791998454
pol          0.3148485673882525
amplitude     37.09340153372006
seed                     5533.0
Name: 100, dtype: float64

This is a pd.Series, and values can be accessed simply by specifying the field:

In [61]:
inj_parameters['ccsn_pan21_s40fr'].loc[100]['time']

np.float64(1402360714.3399901)

Now let's say we want to combine injection parameters from different injection wave types in a single dataframe, for example to get for every inj wave type the injection with greater amplitude. There would be problems in that each injection type is described by different parameters. the best way I found is:

1.   fill a dictionary first, where the keys will be the row indices of the DataFrame, and the content a pd.Series that will become the actual row itself. The column indices will be merged, filling with NaN where some of the rows don't have that particular field.
2.   just input the dictionary to the DataFrame constructor

So we get:

In [62]:
inj_parameters_max_amp_dict = {}
# get injection with maximum amplitude for each wave type
for inj_wave_type in inj_parameters:
  inj_parameters_max_amp_dict[inj_wave_type] = inj_parameters[inj_wave_type].loc[inj_parameters[inj_wave_type]['amplitude'].idxmax()]

inj_parameters_max_amp_df = pd.DataFrame(inj_parameters_max_amp_dict).transpose().sort_values(by='amplitude', ascending=False)
del inj_parameters_max_amp_dict
inj_parameters_max_amp_df

,amplitude,bandwidth,dec,duration,eccentricity,frequency,phase,pol,quality,ra,seed,time
cbc_bbh125,164.44454677050774,NaN,0.0840205511813443,NaN,NaN,NaN,NaN,3.2840321996684776,NaN,6.253496171322681,5533.0,1402327559.321994
ccsn_pan18_s402d-dd2,46.80541788218131,NaN,1.1350370134192302,NaN,NaN,NaN,NaN,1.3457838921138343,NaN,4.985074553850091,5533.0,1402265088.2911243
ccsn_pan21_s40fr,37.09340153372006,NaN,0.34313265791998454,NaN,NaN,NaN,NaN,0.3148485673882525,NaN,0.6646404911099573,5533.0,1402360714.3399901
che_2,16.11433705845197,NaN,1.339366338509362,NaN,NaN,NaN,NaN,5.626050258713189,NaN,3.5142461185502762,5533.0,1402223251.5243294
cbc_bbh10,12.341295080615499,NaN,-1.0348338801848587,NaN,NaN,NaN,NaN,3.545925523525306,NaN,6.1649265908343995,5533.0,1402315715.86411
...,...,...,...,...,...,...,...,...,...,...,...,...
wnb_295_305_t400,6.562028530961173e-38,10.0,-0.734666220887999,0.4,0.5880792951065662,300.0,3.1998512345981465,5.319442942774546,NaN,2.667109595661014,5533.0,1402466246.773795
wnb_80_90_t200,3.4178839488728417e-38,10.0,-1.0404112260739846,0.2,0.1303236925573562,85.0,0.0981650844632566,1.2392608511518273,NaN,5.100703436932842,5533.0,1402333924.2166963
wnb_100_200_t100,2.5904886308517063e-38,100.0,-0.10230667527534433,0.1,0.10600013736342928,150.0,4.963929238901601,1.913116401414095,NaN,5.54841404160853,5533.0,1402244030.5541804
wnb_30_50_t1800,2.1357822601759149e-38,20.0,0.016727086786663764,1.8,0.13075236725389372,40.0,3.5101143809839783,5.509729523949598,NaN,5.244397164720279,5533.0,1402308080.1382647
wnb_55_65_t500,7.27556104868897e-39,10.0,-0.08917874299731875,0.5,0.17038451961513013,60.0,0.09727857792008032,5.978927664287567,NaN,1.08750854577805,5533.0,1402319545.1941736

So to get some parameter:

In [63]:
inj_parameters_max_amp_df.loc['cbc_bbh125']['time']

np.float64(1402327559.321994)

Now let's check if this inj type `cbc_bbh125` is of type WAVE, i.e. has a duration described by a time series. Let's print its `inj_attributes`:

In [64]:
inj_attributes['cbc_bbh125']

{'hrss_norm': np.float64(1e-22),
 'sampling_rate': np.float64(16384.0),
 'type': 'WAVE'}

In [65]:
if inj_attributes['cbc_bbh125']['type'] == 'WAVE':
  print("Injection 'cbc_bbh125' described by a time series, check inj_STRAIN_time_series!")
  display(inj_STRAIN_time_series['cbc_bbh125'])

Injection 'cbc_bbh125' described by a time series, check inj_STRAIN_time_series!

                     hcross                  hplus             times
0     2.415735850416778e-22  1.346098112206854e-22  -0.0460205078125
1     2.419119100312408e-22  1.340086374837242e-22 -0.04595947265625
2     2.422487840161079e-22  1.334064681801457e-22     -0.0458984375
3     2.425842037533694e-22  1.328033066460533e-22 -0.04583740234375
4     2.429181660069641e-22  1.321991562284579e-22  -0.0457763671875
...                     ...                    ...               ...
33945 1.154926687588049e-26 -4.073621858212475e-27  2.02581787109375
33946 1.154927996631586e-26 -4.073519443521208e-27     2.02587890625
33947 1.154929295766943e-26 -4.073417053059075e-27  2.02593994140625
33948 1.154930587793702e-26 -4.073314679752676e-27   2.0260009765625
33949 1.154931875511331e-26 -4.073212316527205e-27  2.02606201171875

[33950 rows x 3 columns]

So what's the duration of the injection of maximum amplitude of type `cbc_bbh125`?

In [66]:
def inj_duration(inj_wave_type):
  if inj_attributes[inj_wave_type]['type'] != 'WAVE':
    print("This injection type has no waveform described by a time series!")
    return None
  return(len(inj_STRAIN_time_series[inj_wave_type]) / inj_attributes[inj_wave_type]['sampling_rate'])

In [67]:
# duration of the time series
print("Injection duration is:", inj_duration('cbc_bbh125'), "s")

Injection duration is: 2.0721435546875 s

## INJ TIME at the ITFs

The injection times are defined at the centre of the earth. So depending on the orientation and propagation direction of the grav wave the actual time at the interferometers can be greater of lesser.

This function returns a dictionary with an entry for each itf, with the corresponding time.

In [68]:
from pycbc.detector import Detector
def inj2ifo_time(inj_ra, inj_dec, inj_time_gps, ifo_list=['H1', 'L1']):
  ifo_inj_time = {}

  for IFO in ifo_list:
    det = Detector(IFO)
    #print("inj_max_amp_time_delay_from", IFO, ":", det.time_delay_from_earth_center(inj_ra, inj_dec, inj_time_gps), "s")
    ifo_inj_time[IFO] = inj_time_gps + det.time_delay_from_earth_center(inj_ra, inj_dec, inj_time_gps)

  return ifo_inj_time

For example, let's add to the previous dataframe tthe fields for the time of the innjections at the itfs:

In [69]:
inj_parameters_max_amp_df['time_at_H1'] = None
inj_parameters_max_amp_df['time_at_L1'] = None

for inj_wave_type, inj_parameters_max_amp in inj_parameters_max_amp_df.iterrows():
  inj_max_amp_time_at_IFO = inj2ifo_time(inj_parameters_max_amp_df.loc[inj_wave_type]['ra'], inj_parameters_max_amp_df.loc[inj_wave_type]['dec'], inj_parameters_max_amp_df.loc[inj_wave_type]['time'])
  for IFO in inj_max_amp_time_at_IFO:
    inj_parameters_max_amp_df.loc[inj_wave_type, 'time_at_'+IFO] = inj_max_amp_time_at_IFO[IFO]

inj_parameters_max_amp_df

,amplitude,bandwidth,dec,duration,eccentricity,frequency,phase,pol,quality,ra,seed,time,time_at_H1,time_at_L1
cbc_bbh125,164.44454677050774,NaN,0.0840205511813443,NaN,NaN,NaN,NaN,3.2840321996684776,NaN,6.253496171322681,5533.0,1402327559.321994,1402327559.3066525,1402327559.3081243
ccsn_pan18_s402d-dd2,46.80541788218131,NaN,1.1350370134192302,NaN,NaN,NaN,NaN,1.3457838921138343,NaN,4.985074553850091,5533.0,1402265088.2911243,1402265088.2833533,1402265088.2875996
ccsn_pan21_s40fr,37.09340153372006,NaN,0.34313265791998454,NaN,NaN,NaN,NaN,0.3148485673882525,NaN,0.6646404911099573,5533.0,1402360714.3399901,1402360714.3406482,1402360714.3502567
che_2,16.11433705845197,NaN,1.339366338509362,NaN,NaN,NaN,NaN,5.626050258713189,NaN,3.5142461185502762,5533.0,1402223251.5243294,1402223251.5098212,1402223251.5163288
cbc_bbh10,12.341295080615499,NaN,-1.0348338801848587,NaN,NaN,NaN,NaN,3.545925523525306,NaN,6.1649265908343995,5533.0,1402315715.86411,1402315715.8706987,1402315715.863994
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
wnb_295_305_t400,6.562028530961173e-38,10.0,-0.734666220887999,0.4,0.5880792951065662,300.0,3.1998512345981465,5.319442942774546,NaN,2.667109595661014,5533.0,1402466246.773795,1402466246.7823927,1402466246.785595
wnb_80_90_t200,3.4178839488728417e-38,10.0,-1.0404112260739846,0.2,0.1303236925573562,85.0,0.0981650844632566,1.2392608511518273,NaN,5.100703436932842,5533.0,1402333924.2166963,1402333924.2323265,1402333924.2328043
wnb_100_200_t100,2.5904886308517063e-38,100.0,-0.10230667527534433,0.1,0.10600013736342928,150.0,4.963929238901601,1.913116401414095,NaN,5.54841404160853,5533.0,1402244030.5541804,1402244030.5501726,1402244030.5572472
wnb_30_50_t1800,2.1357822601759149e-38,20.0,0.016727086786663764,1.8,0.13075236725389372,40.0,3.5101143809839783,5.509729523949598,NaN,5.244397164720279,5533.0,1402308080.1382647,1402308080.1234498,1402308080.1209948
wnb_55_65_t500,7.27556104868897e-39,10.0,-0.08917874299731875,0.5,0.17038451961513013,60.0,0.09727857792008032,5.978927664287567,NaN,1.08750854577805,5533.0,1402319545.1941736,1402319545.1933384,1402319545.1840665

## Let's search triggers around injections

Let's search for each of the injections of the `inj_parameters_max_amp_df` df

In [70]:
time_window_around_inj = 5#s
for inj_wave_type, inj_parameters_max_amp in inj_parameters_max_amp_df.iterrows():
  print("--------------------------->INJECTION TYPE: ", inj_wave_type)
  print("maximum amplitude INJECTION parameters:")
  display(inj_parameters_max_amp_df.loc[inj_wave_type].dropna().to_frame().transpose())
  print()
  for IFO in ['H', 'L']:
    mask_triggers_near_inj = (triggers_df[IFO]['gpsPeak'] < inj_parameters_max_amp['time_at_'+IFO+'1'] + time_window_around_inj) & (triggers_df[IFO]['gpsPeak'] > inj_parameters_max_amp['time_at_'+IFO+'1'] - time_window_around_inj)
    print("IFO:", IFO,', TRIGGERS:', len(triggers_df[IFO][mask_triggers_near_inj]), "found in a time window of ", time_window_around_inj, "s around the maximum amplitude injection of type", inj_wave_type)

    for trigger_index, trigger_parameters in triggers_df[IFO][mask_triggers_near_inj].iterrows():
      print("trigger number:", trigger_index, ", delay from inj:", abs(trigger_parameters['gpsPeak']-inj_parameters_max_amp['time_at_'+IFO+'1']), 's')
    print("TRIGGER parameters:")
    display(triggers_df[IFO][mask_triggers_near_inj][triggers_df[IFO].columns[:triggers_df[IFO].columns.get_loc('wt0')]])
    print()
  print()

--------------------------->INJECTION TYPE:  cbc_bbh125
maximum amplitude INJECTION parameters:

,amplitude,dec,pol,ra,seed,time,time_at_H1,time_at_L1
cbc_bbh125,164.44454677050774,0.0840205511813443,3.2840321996684776,6.253496171322681,5533.0,1402327559.321994,1402327559.3066525,1402327559.3081243

IFO: H , TRIGGERS: 0 found in a time window of  5 s around the maximum amplitude injection of type cbc_bbh125
TRIGGER parameters:

Empty DataFrame
Columns: [gps, gpsPeak, duration, EnWDF, snrMean, snrPeak, freqMin, freqMean, freqMax, freqPeak, wave]
Index: []

IFO: L , TRIGGERS: 1 found in a time window of  5 s around the maximum amplitude injection of type cbc_bbh125
trigger number: 1327 , delay from inj: 3.306659460067749 s
TRIGGER parameters:

,gps,gpsPeak,duration,EnWDF,snrMean,snrPeak,freqMin,freqMean,freqMax,freqPeak,wave
1327,1402327555.8359375,1402327556.0014648,0.14208984375,0.8086338110139039,0.4343601809024163,3.692327150736425,4.0,60.46153846153846,128.0,20.0,BsplineC309

--------------------------->INJECTION TYPE:  ccsn_pan18_s402d-dd2
maximum amplitude INJECTION parameters:

,amplitude,dec,pol,ra,seed,time,time_at_H1,time_at_L1
ccsn_pan18_s402d-dd2,46.80541788218131,1.1350370134192302,1.3457838921138343,4.985074553850091,5533.0,1402265088.2911243,1402265088.2833533,1402265088.2875996

IFO: H , TRIGGERS: 0 found in a time window of  5 s around the maximum amplitude injection of type ccsn_pan18_s402d-dd2
TRIGGER parameters:

Empty DataFrame
Columns: [gps, gpsPeak, duration, EnWDF, snrMean, snrPeak, freqMin, freqMean, freqMax, freqPeak, wave]
Index: []

IFO: L , TRIGGERS: 1 found in a time window of  5 s around the maximum amplitude injection of type ccsn_pan18_s402d-dd2
trigger number: 11562 , delay from inj: 4.287599563598633 s
TRIGGER parameters:

,gps,gpsPeak,duration,EnWDF,snrMean,snrPeak,freqMin,freqMean,freqMax,freqPeak,wave
11562,1402265083.8203125,1402265084.0,0.00341796875,1.1367955394653284,0.9339547895826964,15.394100360412809,36.0,189.84615384615384,244.0,168.0,BsplineC206

--------------------------->INJECTION TYPE:  ccsn_pan21_s40fr
maximum amplitude INJECTION parameters:

,amplitude,dec,pol,ra,seed,time,time_at_H1,time_at_L1
ccsn_pan21_s40fr,37.09340153372006,0.34313265791998454,0.3148485673882525,0.6646404911099573,5533.0,1402360714.3399901,1402360714.3406482,1402360714.3502567

IFO: H , TRIGGERS: 0 found in a time window of  5 s around the maximum amplitude injection of type ccsn_pan21_s40fr
TRIGGER parameters:

Empty DataFrame
Columns: [gps, gpsPeak, duration, EnWDF, snrMean, snrPeak, freqMin, freqMean, freqMax, freqPeak, wave]
Index: []

IFO: L , TRIGGERS: 0 found in a time window of  5 s around the maximum amplitude injection of type ccsn_pan21_s40fr
TRIGGER parameters:

Empty DataFrame
Columns: [gps, gpsPeak, duration, EnWDF, snrMean, snrPeak, freqMin, freqMean, freqMax, freqPeak, wave]
Index: []

--------------------------->INJECTION TYPE:  che_2
maximum amplitude INJECTION parameters:

,amplitude,dec,pol,ra,seed,time,time_at_H1,time_at_L1
che_2,16.11433705845197,1.339366338509362,5.626050258713189,3.5142461185502762,5533.0,1402223251.5243294,1402223251.5098212,1402223251.5163288

IFO: H , TRIGGERS: 0 found in a time window of  5 s around the maximum amplitude injection of type che_2
TRIGGER parameters:

Empty DataFrame
Columns: [gps, gpsPeak, duration, EnWDF, snrMean, snrPeak, freqMin, freqMean, freqMax, freqPeak, wave]
Index: []

IFO: L , TRIGGERS: 0 found in a time window of  5 s around the maximum amplitude injection of type che_2
TRIGGER parameters:

Empty DataFrame
Columns: [gps, gpsPeak, duration, EnWDF, snrMean, snrPeak, freqMin, freqMean, freqMax, freqPeak, wave]
Index: []

--------------------------->INJECTION TYPE:  cbc_bbh10
maximum amplitude INJECTION parameters:

,amplitude,dec,pol,ra,seed,time,time_at_H1,time_at_L1
cbc_bbh10,12.341295080615499,-1.0348338801848587,3.545925523525306,6.1649265908343995,5533.0,1402315715.86411,1402315715.8706987,1402315715.863994

IFO: H , TRIGGERS: 0 found in a time window of  5 s around the maximum amplitude injection of type cbc_bbh10
TRIGGER parameters:

Empty DataFrame
Columns: [gps, gpsPeak, duration, EnWDF, snrMean, snrPeak, freqMin, freqMean, freqMax, freqPeak, wave]
Index: []

IFO: L , TRIGGERS: 1 found in a time window of  5 s around the maximum amplitude injection of type cbc_bbh10
trigger number: 384 , delay from inj: 0.13698267936706543 s
TRIGGER parameters:

,gps,gpsPeak,duration,EnWDF,snrMean,snrPeak,freqMin,freqMean,freqMax,freqPeak,wave
384,1402315715.7734375,1402315716.0009766,0.01220703125,2.3683341606160297,1.155059031127011,11.896958154233497,4.0,54.30769230769231,112.0,20.0,BsplineC309

--------------------------->INJECTION TYPE:  ccsn_rad19_s10
maximum amplitude INJECTION parameters:

,amplitude,dec,pol,ra,seed,time,time_at_H1,time_at_L1
ccsn_rad19_s10,9.626321196865183,-0.32136562421368314,2.0916972796428803,5.443197490092411,5533.0,1402283886.2370512,1402283886.2488406,1402283886.2408297

IFO: H , TRIGGERS: 1 found in a time window of  5 s around the maximum amplitude injection of type ccsn_rad19_s10
trigger number: 3726 , delay from inj: 2.247864007949829 s
TRIGGER parameters:

,gps,gpsPeak,duration,EnWDF,snrMean,snrPeak,freqMin,freqMean,freqMax,freqPeak,wave
3726,1402283883.84375,1402283884.0009766,0.0205078125,0.5309145686314838,0.5790465839432236,5.878100677442799,32.0,89.23076923076923,148.0,80.0,BsplineC309

IFO: L , TRIGGERS: 1 found in a time window of  5 s around the maximum amplitude injection of type ccsn_rad19_s10
trigger number: 12156 , delay from inj: 2.2408297061920166 s
TRIGGER parameters:

,gps,gpsPeak,duration,EnWDF,snrMean,snrPeak,freqMin,freqMean,freqMax,freqPeak,wave
12156,1402283883.8671875,1402283884.0,0.00341796875,1.1790799821269369,0.925790713499619,15.53552504531619,152.0,204.30769230769232,272.0,172.0,BsplineC206

--------------------------->INJECTION TYPE:  cbc_ebbh_m200q50e36
maximum amplitude INJECTION parameters:

,amplitude,dec,pol,ra,seed,time,time_at_H1,time_at_L1
cbc_ebbh_m200q50e36,7.849939737231132,0.6578767968797185,3.633905398820376,2.7938966187469667,5533.0,1402371651.9880528,1402371651.9695895,1402371651.9758615

IFO: H , TRIGGERS: 0 found in a time window of  5 s around the maximum amplitude injection of type cbc_ebbh_m200q50e36
TRIGGER parameters:

Empty DataFrame
Columns: [gps, gpsPeak, duration, EnWDF, snrMean, snrPeak, freqMin, freqMean, freqMax, freqPeak, wave]
Index: []

IFO: L , TRIGGERS: 0 found in a time window of  5 s around the maximum amplitude injection of type cbc_ebbh_m200q50e36
TRIGGER parameters:

Empty DataFrame
Columns: [gps, gpsPeak, duration, EnWDF, snrMean, snrPeak, freqMin, freqMean, freqMax, freqPeak, wave]
Index: []

--------------------------->INJECTION TYPE:  cbc_ebbh_m100q100e19
maximum amplitude INJECTION parameters:

,amplitude,dec,pol,ra,seed,time,time_at_H1,time_at_L1
cbc_ebbh_m100q100e19,6.762790916197658,0.36506517384334963,5.947437726855461,5.493890378024596,5533.0,1402439227.6956298,1402439227.703473,1402439227.7083437

IFO: H , TRIGGERS: 0 found in a time window of  5 s around the maximum amplitude injection of type cbc_ebbh_m100q100e19
TRIGGER parameters:

Empty DataFrame
Columns: [gps, gpsPeak, duration, EnWDF, snrMean, snrPeak, freqMin, freqMean, freqMax, freqPeak, wave]
Index: []

IFO: L , TRIGGERS: 0 found in a time window of  5 s around the maximum amplitude injection of type cbc_ebbh_m100q100e19
TRIGGER parameters:

Empty DataFrame
Columns: [gps, gpsPeak, duration, EnWDF, snrMean, snrPeak, freqMin, freqMean, freqMax, freqPeak, wave]
Index: []

--------------------------->INJECTION TYPE:  cbc_bbh50
maximum amplitude INJECTION parameters:

,amplitude,dec,pol,ra,seed,time,time_at_H1,time_at_L1
cbc_bbh50,5.243293536979949,0.10425811758859069,3.0453667925620906,2.439594535512329,5533.0,1402373279.3338833,1402373279.3262758,1402373279.3341405

IFO: H , TRIGGERS: 0 found in a time window of  5 s around the maximum amplitude injection of type cbc_bbh50
TRIGGER parameters:

Empty DataFrame
Columns: [gps, gpsPeak, duration, EnWDF, snrMean, snrPeak, freqMin, freqMean, freqMax, freqPeak, wave]
Index: []

IFO: L , TRIGGERS: 0 found in a time window of  5 s around the maximum amplitude injection of type cbc_bbh50
TRIGGER parameters:

Empty DataFrame
Columns: [gps, gpsPeak, duration, EnWDF, snrMean, snrPeak, freqMin, freqMean, freqMax, freqPeak, wave]
Index: []

--------------------------->INJECTION TYPE:  ccsn_and16_s20s
maximum amplitude INJECTION parameters:

,amplitude,dec,pol,ra,seed,time,time_at_H1,time_at_L1
ccsn_and16_s20s,4.963481917641489,-0.5325391973932887,1.3113509163180495,5.833371369635343,5533.0,1402414826.3499827,1402414826.348803,1402414826.3509479

IFO: H , TRIGGERS: 0 found in a time window of  5 s around the maximum amplitude injection of type ccsn_and16_s20s
TRIGGER parameters:

Empty DataFrame
Columns: [gps, gpsPeak, duration, EnWDF, snrMean, snrPeak, freqMin, freqMean, freqMax, freqPeak, wave]
Index: []

IFO: L , TRIGGERS: 0 found in a time window of  5 s around the maximum amplitude injection of type ccsn_and16_s20s
TRIGGER parameters:

Empty DataFrame
Columns: [gps, gpsPeak, duration, EnWDF, snrMean, snrPeak, freqMin, freqMean, freqMax, freqPeak, wave]
Index: []

--------------------------->INJECTION TYPE:  cbc_bbh35
maximum amplitude INJECTION parameters:

,amplitude,dec,pol,ra,seed,time,time_at_H1,time_at_L1
cbc_bbh35,4.735687520647014,-0.8605983431816028,4.986315185632162,5.142696751901265,5533.0,1402281554.4973123,1402281554.5125978,1402281554.504172

IFO: H , TRIGGERS: 2 found in a time window of  5 s around the maximum amplitude injection of type cbc_bbh35
trigger number: 3607 , delay from inj: 0.5121095180511475 s
trigger number: 3608 , delay from inj: 0.5121095180511475 s
TRIGGER parameters:

,gps,gpsPeak,duration,EnWDF,snrMean,snrPeak,freqMin,freqMean,freqMax,freqPeak,wave
3607,1402281553.7578125,1402281554.0004883,0.0048828125,1.0148118308305367,1.0419988775618596,12.228199575895038,24.0,74.0,124.0,36.0,BsplineC206
3608,1402281554.0,1402281554.0004883,0.24951171875,0.9777017225061622,1.1292711017611328,12.544104118094946,28.0,79.23076923076923,140.0,72.0,BsplineC309

IFO: L , TRIGGERS: 0 found in a time window of  5 s around the maximum amplitude injection of type cbc_bbh35
TRIGGER parameters:

Empty DataFrame
Columns: [gps, gpsPeak, duration, EnWDF, snrMean, snrPeak, freqMin, freqMean, freqMax, freqPeak, wave]
Index: []

--------------------------->INJECTION TYPE:  ccsn_mez23_d15
maximum amplitude INJECTION parameters:

,amplitude,dec,pol,ra,seed,time,time_at_H1,time_at_L1
ccsn_mez23_d15,4.484278038815722,0.11088941735309783,4.007546467344519,5.085271592914525,5533.0,1402510095.6324604,1402510095.6392856,1402510095.6477

IFO: H , TRIGGERS: 0 found in a time window of  5 s around the maximum amplitude injection of type ccsn_mez23_d15
TRIGGER parameters:

Empty DataFrame
Columns: [gps, gpsPeak, duration, EnWDF, snrMean, snrPeak, freqMin, freqMean, freqMax, freqPeak, wave]
Index: []

IFO: L , TRIGGERS: 0 found in a time window of  5 s around the maximum amplitude injection of type ccsn_mez23_d15
TRIGGER parameters:

Empty DataFrame
Columns: [gps, gpsPeak, duration, EnWDF, snrMean, snrPeak, freqMin, freqMean, freqMax, freqPeak, wave]
Index: []

--------------------------->INJECTION TYPE:  ccsn_pow21_z100
maximum amplitude INJECTION parameters:

,amplitude,dec,pol,ra,seed,time,time_at_H1,time_at_L1
ccsn_pow21_z100,4.2718540685911375,0.520115679092806,1.6261394041355735,6.2752511925994705,5533.0,1402329468.2498376,1402329468.2304726,1402329468.2345915

IFO: H , TRIGGERS: 0 found in a time window of  5 s around the maximum amplitude injection of type ccsn_pow21_z100
TRIGGER parameters:

Empty DataFrame
Columns: [gps, gpsPeak, duration, EnWDF, snrMean, snrPeak, freqMin, freqMean, freqMax, freqPeak, wave]
Index: []

IFO: L , TRIGGERS: 0 found in a time window of  5 s around the maximum amplitude injection of type ccsn_pow21_z100
TRIGGER parameters:

Empty DataFrame
Columns: [gps, gpsPeak, duration, EnWDF, snrMean, snrPeak, freqMin, freqMean, freqMax, freqPeak, wave]
Index: []

--------------------------->INJECTION TYPE:  cbc_ebbh_m175q50e51
maximum amplitude INJECTION parameters:

,amplitude,dec,pol,ra,seed,time,time_at_H1,time_at_L1
cbc_ebbh_m175q50e51,3.7983328565569647,0.6239543033813456,1.4544486810910122,0.44329544855299685,5533.0,1402404958.5788841,1402404958.5618784,1402404958.558525

IFO: H , TRIGGERS: 0 found in a time window of  5 s around the maximum amplitude injection of type cbc_ebbh_m175q50e51
TRIGGER parameters:

Empty DataFrame
Columns: [gps, gpsPeak, duration, EnWDF, snrMean, snrPeak, freqMin, freqMean, freqMax, freqPeak, wave]
Index: []

IFO: L , TRIGGERS: 0 found in a time window of  5 s around the maximum amplitude injection of type cbc_ebbh_m175q50e51
TRIGGER parameters:

Empty DataFrame
Columns: [gps, gpsPeak, duration, EnWDF, snrMean, snrPeak, freqMin, freqMean, freqMax, freqPeak, wave]
Index: []

--------------------------->INJECTION TYPE:  ccsn_pow18_s18
maximum amplitude INJECTION parameters:

,amplitude,dec,pol,ra,seed,time,time_at_H1,time_at_L1
ccsn_pow18_s18,3.7275758043187364,-0.5221963659300303,0.6992489779439639,4.531164377974312,5533.0,1402224311.1221492,1402224311.1205652,1402224311.1226268

IFO: H , TRIGGERS: 0 found in a time window of  5 s around the maximum amplitude injection of type ccsn_pow18_s18
TRIGGER parameters:

Empty DataFrame
Columns: [gps, gpsPeak, duration, EnWDF, snrMean, snrPeak, freqMin, freqMean, freqMax, freqPeak, wave]
Index: []

IFO: L , TRIGGERS: 0 found in a time window of  5 s around the maximum amplitude injection of type ccsn_pow18_s18
TRIGGER parameters:

Empty DataFrame
Columns: [gps, gpsPeak, duration, EnWDF, snrMean, snrPeak, freqMin, freqMean, freqMax, freqPeak, wave]
Index: []

--------------------------->INJECTION TYPE:  cbc_ebbh_m60q50e20
maximum amplitude INJECTION parameters:

,amplitude,dec,pol,ra,seed,time,time_at_H1,time_at_L1
cbc_ebbh_m60q50e20,3.642834952559902,0.143469816734389,4.526135795379268,0.1540361841437115,5533.0,1402454104.6247127,1402454104.63698,1402454104.6398823

IFO: H , TRIGGERS: 0 found in a time window of  5 s around the maximum amplitude injection of type cbc_ebbh_m60q50e20
TRIGGER parameters:

Empty DataFrame
Columns: [gps, gpsPeak, duration, EnWDF, snrMean, snrPeak, freqMin, freqMean, freqMax, freqPeak, wave]
Index: []

IFO: L , TRIGGERS: 1 found in a time window of  5 s around the maximum amplitude injection of type cbc_ebbh_m60q50e20
trigger number: 3475 , delay from inj: 4.360117673873901 s
TRIGGER parameters:

,gps,gpsPeak,duration,EnWDF,snrMean,snrPeak,freqMin,freqMean,freqMax,freqPeak,wave
3475,1402454108.9921875,1402454109.0,0.125,1.0978782818324846,0.8665269419002554,13.168512825772009,36.0,182.6153846153846,244.0,172.0,BsplineC206

--------------------------->INJECTION TYPE:  ccsn_and16_s20
maximum amplitude INJECTION parameters:

,amplitude,dec,pol,ra,seed,time,time_at_H1,time_at_L1
ccsn_and16_s20,3.640478633532416,-0.2725506218160261,2.563629787141858,5.339998048930936,5533.0,1402270787.0115442,1402270787.0295422,1402270787.027981

IFO: H , TRIGGERS: 1 found in a time window of  5 s around the maximum amplitude injection of type ccsn_and16_s20
trigger number: 12971 , delay from inj: 0.028565645217895508 s
TRIGGER parameters:

,gps,gpsPeak,duration,EnWDF,snrMean,snrPeak,freqMin,freqMean,freqMax,freqPeak,wave
12971,1402270786.8203125,1402270787.0009766,0.150390625,0.9667803582026931,0.9248888530504716,10.695072944751017,8.0,66.3076923076923,156.0,64.0,BsplineC309

IFO: L , TRIGGERS: 1 found in a time window of  5 s around the maximum amplitude injection of type ccsn_and16_s20
trigger number: 11733 , delay from inj: 3.0279810428619385 s
TRIGGER parameters:

,gps,gpsPeak,duration,EnWDF,snrMean,snrPeak,freqMin,freqMean,freqMax,freqPeak,wave
11733,1402270783.9453125,1402270784.0,0.00537109375,0.6138005706090572,0.5249436165455704,8.915018690747486,156.0,206.0,256.0,208.0,BsplineC103

--------------------------->INJECTION TYPE:  ccsn_oco18_mesa20pertlr
maximum amplitude INJECTION parameters:

,amplitude,dec,pol,ra,seed,time,time_at_H1,time_at_L1
ccsn_oco18_mesa20pertlr,3.293037142548756,0.07492665659407372,0.8621922046295688,1.4114300046850987,5533.0,1402404381.6006348,1402404381.6033862,1402404381.595659

IFO: H , TRIGGERS: 0 found in a time window of  5 s around the maximum amplitude injection of type ccsn_oco18_mesa20pertlr
TRIGGER parameters:

Empty DataFrame
Columns: [gps, gpsPeak, duration, EnWDF, snrMean, snrPeak, freqMin, freqMean, freqMax, freqPeak, wave]
Index: []

IFO: L , TRIGGERS: 0 found in a time window of  5 s around the maximum amplitude injection of type ccsn_oco18_mesa20pertlr
TRIGGER parameters:

Empty DataFrame
Columns: [gps, gpsPeak, duration, EnWDF, snrMean, snrPeak, freqMin, freqMean, freqMax, freqPeak, wave]
Index: []

--------------------------->INJECTION TYPE:  ccsn_pow20_y20
maximum amplitude INJECTION parameters:

,amplitude,dec,pol,ra,seed,time,time_at_H1,time_at_L1
ccsn_pow20_y20,3.1768657566183793,1.116862430843186,2.844234149557446,4.159996087381149,5533.0,1402487668.1879172,1402487668.1735704,1402487668.181481

IFO: H , TRIGGERS: 1 found in a time window of  5 s around the maximum amplitude injection of type ccsn_pow20_y20
trigger number: 2422 , delay from inj: 1.8269178867340088 s
TRIGGER parameters:

,gps,gpsPeak,duration,EnWDF,snrMean,snrPeak,freqMin,freqMean,freqMax,freqPeak,wave
2422,1402487669.9453125,1402487670.0004883,0.01416015625,0.9380319076870428,1.0227412917427352,11.30822768396072,24.0,74.0,124.0,36.0,BsplineC206

IFO: L , TRIGGERS: 0 found in a time window of  5 s around the maximum amplitude injection of type ccsn_pow20_y20
TRIGGER parameters:

Empty DataFrame
Columns: [gps, gpsPeak, duration, EnWDF, snrMean, snrPeak, freqMin, freqMean, freqMax, freqPeak, wave]
Index: []

--------------------------->INJECTION TYPE:  ccsn_mez23_d9
maximum amplitude INJECTION parameters:

,amplitude,dec,pol,ra,seed,time,time_at_H1,time_at_L1
ccsn_mez23_d9,2.9078296162406785,-1.1834095129541513,1.4405072499785099,2.8560402684340285,5533.0,1402213192.4692209,1402213192.4837172,1402213192.4828095

IFO: H , TRIGGERS: 0 found in a time window of  5 s around the maximum amplitude injection of type ccsn_mez23_d9
TRIGGER parameters:

Empty DataFrame
Columns: [gps, gpsPeak, duration, EnWDF, snrMean, snrPeak, freqMin, freqMean, freqMax, freqPeak, wave]
Index: []

IFO: L , TRIGGERS: 0 found in a time window of  5 s around the maximum amplitude injection of type ccsn_mez23_d9
TRIGGER parameters:

Empty DataFrame
Columns: [gps, gpsPeak, duration, EnWDF, snrMean, snrPeak, freqMin, freqMean, freqMax, freqPeak, wave]
Index: []

--------------------------->INJECTION TYPE:  ccsn_mor18_m13
maximum amplitude INJECTION parameters:

,amplitude,dec,pol,ra,seed,time,time_at_H1,time_at_L1
ccsn_mor18_m13,2.6805575687397827,0.9928645946282,3.7362898196994214,4.149845328185716,5533.0,1402486769.7969623,1402486769.782976,1402486769.7914634

IFO: H , TRIGGERS: 0 found in a time window of  5 s around the maximum amplitude injection of type ccsn_mor18_m13
TRIGGER parameters:

Empty DataFrame
Columns: [gps, gpsPeak, duration, EnWDF, snrMean, snrPeak, freqMin, freqMean, freqMax, freqPeak, wave]
Index: []

IFO: L , TRIGGERS: 0 found in a time window of  5 s around the maximum amplitude injection of type ccsn_mor18_m13
TRIGGER parameters:

Empty DataFrame
Columns: [gps, gpsPeak, duration, EnWDF, snrMean, snrPeak, freqMin, freqMean, freqMax, freqPeak, wave]
Index: []

--------------------------->INJECTION TYPE:  cbc_ebbh_m200q100e70
maximum amplitude INJECTION parameters:

,amplitude,dec,pol,ra,seed,time,time_at_H1,time_at_L1
cbc_ebbh_m200q100e70,2.593291821713806,-0.2033137128536345,3.7971258646217168,0.04965799857047777,5533.0,1402407777.033402,1402407777.0225017,1402407777.0182602

IFO: H , TRIGGERS: 0 found in a time window of  5 s around the maximum amplitude injection of type cbc_ebbh_m200q100e70
TRIGGER parameters:

Empty DataFrame
Columns: [gps, gpsPeak, duration, EnWDF, snrMean, snrPeak, freqMin, freqMean, freqMax, freqPeak, wave]
Index: []

IFO: L , TRIGGERS: 0 found in a time window of  5 s around the maximum amplitude injection of type cbc_ebbh_m200q100e70
TRIGGER parameters:

Empty DataFrame
Columns: [gps, gpsPeak, duration, EnWDF, snrMean, snrPeak, freqMin, freqMean, freqMax, freqPeak, wave]
Index: []

--------------------------->INJECTION TYPE:  che_3
maximum amplitude INJECTION parameters:

,amplitude,dec,pol,ra,seed,time,time_at_H1,time_at_L1
che_3,2.5722308000218264,0.8659331914254649,2.996153275660692,4.035400511886006,5533.0,1402390205.8852637,1402390205.866846,1402390205.8737206

IFO: H , TRIGGERS: 0 found in a time window of  5 s around the maximum amplitude injection of type che_3
TRIGGER parameters:

Empty DataFrame
Columns: [gps, gpsPeak, duration, EnWDF, snrMean, snrPeak, freqMin, freqMean, freqMax, freqPeak, wave]
Index: []

IFO: L , TRIGGERS: 0 found in a time window of  5 s around the maximum amplitude injection of type che_3
TRIGGER parameters:

Empty DataFrame
Columns: [gps, gpsPeak, duration, EnWDF, snrMean, snrPeak, freqMin, freqMean, freqMax, freqPeak, wave]
Index: []

--------------------------->INJECTION TYPE:  proca_w85
maximum amplitude INJECTION parameters:

,amplitude,dec,pol,ra,seed,time,time_at_H1,time_at_L1
proca_w85,2.4486560794689343,0.7503243014532058,3.780124409590155,4.808711166320036,5533.0,1402340095.7878585,1402340095.7868168,1402340095.7939367

IFO: H , TRIGGERS: 0 found in a time window of  5 s around the maximum amplitude injection of type proca_w85
TRIGGER parameters:

Empty DataFrame
Columns: [gps, gpsPeak, duration, EnWDF, snrMean, snrPeak, freqMin, freqMean, freqMax, freqPeak, wave]
Index: []

IFO: L , TRIGGERS: 0 found in a time window of  5 s around the maximum amplitude injection of type proca_w85
TRIGGER parameters:

Empty DataFrame
Columns: [gps, gpsPeak, duration, EnWDF, snrMean, snrPeak, freqMin, freqMean, freqMax, freqPeak, wave]
Index: []

--------------------------->INJECTION TYPE:  cbc_ebbh_m80q100e40
maximum amplitude INJECTION parameters:

,amplitude,dec,pol,ra,seed,time,time_at_H1,time_at_L1
cbc_ebbh_m80q100e40,2.188671736754688,0.626926019350228,5.7632785133522395,2.8276134652639433,5533.0,1402430497.518925,1402430497.5073438,1402430497.502843

IFO: H , TRIGGERS: 1 found in a time window of  5 s around the maximum amplitude injection of type cbc_ebbh_m80q100e40
trigger number: 9520 , delay from inj: 1.5068554878234863 s
TRIGGER parameters:

,gps,gpsPeak,duration,EnWDF,snrMean,snrPeak,freqMin,freqMean,freqMax,freqPeak,wave
9520,1402430495.8515625,1402430496.0004883,0.00390625,1.3508231811126836,1.2345405603613495,14.532600489524889,4.0,65.23076923076923,140.0,20.0,BsplineC309

IFO: L , TRIGGERS: 0 found in a time window of  5 s around the maximum amplitude injection of type cbc_ebbh_m80q100e40
TRIGGER parameters:

Empty DataFrame
Columns: [gps, gpsPeak, duration, EnWDF, snrMean, snrPeak, freqMin, freqMean, freqMax, freqPeak, wave]
Index: []

--------------------------->INJECTION TYPE:  cbc_ebbh_m150q100e59
maximum amplitude INJECTION parameters:

,amplitude,dec,pol,ra,seed,time,time_at_H1,time_at_L1
cbc_ebbh_m150q100e59,2.1872293339371187,-0.4850736368863344,2.922515420108728,2.6632297532316933,5533.0,1402221604.4139318,1402221604.4309156,1402221604.4348009

IFO: H , TRIGGERS: 1 found in a time window of  5 s around the maximum amplitude injection of type cbc_ebbh_m150q100e59
trigger number: 10891 , delay from inj: 4.569572687149048 s
TRIGGER parameters:

,gps,gpsPeak,duration,EnWDF,snrMean,snrPeak,freqMin,freqMean,freqMax,freqPeak,wave
10891,1402221608.890625,1402221609.0004883,0.01220703125,0.8228174068826679,0.8428237264501066,10.788368881271673,12.0,62.0,112.0,20.0,BsplineC206

IFO: L , TRIGGERS: 1 found in a time window of  5 s around the maximum amplitude injection of type cbc_ebbh_m150q100e59
trigger number: 7236 , delay from inj: 4.434312582015991 s
TRIGGER parameters:

,gps,gpsPeak,duration,EnWDF,snrMean,snrPeak,freqMin,freqMean,freqMax,freqPeak,wave
7236,1402221599.875,1402221600.0004883,0.00390625,2.019968432482221,1.7938796557167973,21.831923807399,4.0,57.84615384615385,108.0,44.0,BsplineC206

--------------------------->INJECTION TYPE:  cbc_ebbh_m20q50e60
maximum amplitude INJECTION parameters:

,amplitude,dec,pol,ra,seed,time,time_at_H1,time_at_L1
cbc_ebbh_m20q50e60,2.0967591970174038,-0.030778274174018086,4.606182831369442,1.4035608979292225,5533.0,1402489396.936242,1402489396.9416847,1402489396.9337575

IFO: H , TRIGGERS: 0 found in a time window of  5 s around the maximum amplitude injection of type cbc_ebbh_m20q50e60
TRIGGER parameters:

Empty DataFrame
Columns: [gps, gpsPeak, duration, EnWDF, snrMean, snrPeak, freqMin, freqMean, freqMax, freqPeak, wave]
Index: []

IFO: L , TRIGGERS: 1 found in a time window of  5 s around the maximum amplitude injection of type cbc_ebbh_m20q50e60
trigger number: 4713 , delay from inj: 2.0662424564361572 s
TRIGGER parameters:

,gps,gpsPeak,duration,EnWDF,snrMean,snrPeak,freqMin,freqMean,freqMax,freqPeak,wave
4713,1402489398.859375,1402489399.0,0.0029296875,0.9490458589694912,0.6869682727611668,11.8668938679459,148.0,199.07692307692307,264.0,208.0,BsplineC206

--------------------------->INJECTION TYPE:  cbc_ebbh_m100q50e88
maximum amplitude INJECTION parameters:

,amplitude,dec,pol,ra,seed,time,time_at_H1,time_at_L1
cbc_ebbh_m100q50e88,1.982834791928812,0.6732682902609108,4.026080733345351,2.077749759363351,5533.0,1402507895.182771,1402507895.1694915,1402507895.165497

IFO: H , TRIGGERS: 0 found in a time window of  5 s around the maximum amplitude injection of type cbc_ebbh_m100q50e88
TRIGGER parameters:

Empty DataFrame
Columns: [gps, gpsPeak, duration, EnWDF, snrMean, snrPeak, freqMin, freqMean, freqMax, freqPeak, wave]
Index: []

IFO: L , TRIGGERS: 0 found in a time window of  5 s around the maximum amplitude injection of type cbc_ebbh_m100q50e88
TRIGGER parameters:

Empty DataFrame
Columns: [gps, gpsPeak, duration, EnWDF, snrMean, snrPeak, freqMin, freqMean, freqMax, freqPeak, wave]
Index: []

--------------------------->INJECTION TYPE:  ccsn_pow23_m39-1e12
maximum amplitude INJECTION parameters:

,amplitude,dec,pol,ra,seed,time,time_at_H1,time_at_L1
ccsn_pow23_m39-1e12,1.6817989946655498,0.5410487622091144,5.858202277752373,4.475599641283558,5533.0,1402264681.2068934,1402264681.2092607,1402264681.208258

IFO: H , TRIGGERS: 0 found in a time window of  5 s around the maximum amplitude injection of type ccsn_pow23_m39-1e12
TRIGGER parameters:

Empty DataFrame
Columns: [gps, gpsPeak, duration, EnWDF, snrMean, snrPeak, freqMin, freqMean, freqMax, freqPeak, wave]
Index: []

IFO: L , TRIGGERS: 0 found in a time window of  5 s around the maximum amplitude injection of type ccsn_pow23_m39-1e12
TRIGGER parameters:

Empty DataFrame
Columns: [gps, gpsPeak, duration, EnWDF, snrMean, snrPeak, freqMin, freqMean, freqMax, freqPeak, wave]
Index: []

--------------------------->INJECTION TYPE:  che_1
maximum amplitude INJECTION parameters:

,amplitude,dec,pol,ra,seed,time,time_at_H1,time_at_L1
che_1,1.5319065886204195,-0.7571590689326853,3.1850358839892112,2.1610445482364176,5533.0,1402231821.99675,1402231822.016472,1402231822.010947

IFO: H , TRIGGERS: 1 found in a time window of  5 s around the maximum amplitude injection of type che_1
trigger number: 11486 , delay from inj: 3.015495538711548 s
TRIGGER parameters:

,gps,gpsPeak,duration,EnWDF,snrMean,snrPeak,freqMin,freqMean,freqMax,freqPeak,wave
11486,1402231818.7890625,1402231819.0009766,0.1806640625,0.5558807501432019,0.6220151250088909,6.490176077203604,16.0,93.23076923076924,184.0,76.0,BsplineC309

IFO: L , TRIGGERS: 1 found in a time window of  5 s around the maximum amplitude injection of type che_1
trigger number: 10415 , delay from inj: 1.9890530109405518 s
TRIGGER parameters:

,gps,gpsPeak,duration,EnWDF,snrMean,snrPeak,freqMin,freqMean,freqMax,freqPeak,wave
10415,1402231823.96875,1402231824.0,0.0029296875,1.5867640137983066,1.872903990297945,30.4770297527269,140.0,190.0,240.0,168.0,BsplineC206

--------------------------->INJECTION TYPE:  ccsn_and19_s15fr
maximum amplitude INJECTION parameters:

,amplitude,dec,pol,ra,seed,time,time_at_H1,time_at_L1
ccsn_and19_s15fr,0.09380638008967186,-0.7026897573183004,4.5709539560177435,4.329013690139793,5533.0,1402523838.2295496,1402523838.2471817,1402523838.2400935

IFO: H , TRIGGERS: 0 found in a time window of  5 s around the maximum amplitude injection of type ccsn_and19_s15fr
TRIGGER parameters:

Empty DataFrame
Columns: [gps, gpsPeak, duration, EnWDF, snrMean, snrPeak, freqMin, freqMean, freqMax, freqPeak, wave]
Index: []

IFO: L , TRIGGERS: 0 found in a time window of  5 s around the maximum amplitude injection of type ccsn_and19_s15fr
TRIGGER parameters:

Empty DataFrame
Columns: [gps, gpsPeak, duration, EnWDF, snrMean, snrPeak, freqMin, freqMean, freqMax, freqPeak, wave]
Index: []

--------------------------->INJECTION TYPE:  ga_100
maximum amplitude INJECTION parameters:

,amplitude,dec,duration,pol,ra,seed,time,time_at_H1,time_at_L1
ga_100,1.994540253969544e-16,-1.1514165528708418,0.1,3.6957906163861614,0.7996230162917786,5533.0,1402397283.7754822,1402397283.7905407,1402397283.7829256

IFO: H , TRIGGERS: 2 found in a time window of  5 s around the maximum amplitude injection of type ga_100
trigger number: 9251 , delay from inj: 2.6743297576904297 s
trigger number: 9252 , delay from inj: 3.2104358673095703 s
TRIGGER parameters:

,gps,gpsPeak,duration,EnWDF,snrMean,snrPeak,freqMin,freqMean,freqMax,freqPeak,wave
9251,1402397280.8828125,1402397281.116211,0.2021484375,1.1386001384609254,0.9693869777506022,8.760120366368739,60.0,111.53846153846152,168.0,88.0,BsplineC309
9252,1402397286.9375,1402397287.0009766,0.02001953125,0.8092411333661994,0.8622585844474843,9.363129562795498,24.0,74.46153846153847,128.0,36.0,BsplineC309

IFO: L , TRIGGERS: 1 found in a time window of  5 s around the maximum amplitude injection of type ga_100
trigger number: 1393 , delay from inj: 2.6623198986053467 s
TRIGGER parameters:

,gps,gpsPeak,duration,EnWDF,snrMean,snrPeak,freqMin,freqMean,freqMax,freqPeak,wave
1393,1402397280.90625,1402397281.1206057,0.04638671875,0.7089736063924095,0.3809715751427366,3.2565141302453764,164.0,215.23076923076923,280.0,220.0,BsplineC309

--------------------------->INJECTION TYPE:  sg_14q100
maximum amplitude INJECTION parameters:

,amplitude,dec,eccentricity,frequency,phase,pol,quality,ra,seed,time,time_at_H1,time_at_L1
sg_14q100,6.505829918737247e-20,-0.28895990043493014,0.45567678408708046,14.0,2.455875088883812,0.38278324487586846,100.0,2.98209901276608,5533.0,1402320395.4900842,1402320395.508445,1402320395.5094104

IFO: H , TRIGGERS: 1 found in a time window of  5 s around the maximum amplitude injection of type sg_14q100
trigger number: 5474 , delay from inj: 1.5079567432403564 s
TRIGGER parameters:

,gps,gpsPeak,duration,EnWDF,snrMean,snrPeak,freqMin,freqMean,freqMax,freqPeak,wave
5474,1402320393.8515625,1402320394.0004883,0.02978515625,0.764045944852802,0.8802832535469208,9.644798992259556,24.0,75.38461538461539,144.0,36.0,BsplineC206

IFO: L , TRIGGERS: 0 found in a time window of  5 s around the maximum amplitude injection of type sg_14q100
TRIGGER parameters:

Empty DataFrame
Columns: [gps, gpsPeak, duration, EnWDF, snrMean, snrPeak, freqMin, freqMean, freqMax, freqPeak, wave]
Index: []

--------------------------->INJECTION TYPE:  cs_kinkkink
maximum amplitude INJECTION parameters:

,amplitude,dec,pol,ra,seed,time,time_at_H1,time_at_L1
cs_kinkkink,4.6396755412705013e-20,0.6910608753449126,0.3624660083760199,5.754237999082277,5533.0,1402423656.4421978,1402423656.4316795,1402423656.4412901

IFO: H , TRIGGERS: 0 found in a time window of  5 s around the maximum amplitude injection of type cs_kinkkink
TRIGGER parameters:

Empty DataFrame
Columns: [gps, gpsPeak, duration, EnWDF, snrMean, snrPeak, freqMin, freqMean, freqMax, freqPeak, wave]
Index: []

IFO: L , TRIGGERS: 0 found in a time window of  5 s around the maximum amplitude injection of type cs_kinkkink
TRIGGER parameters:

Empty DataFrame
Columns: [gps, gpsPeak, duration, EnWDF, snrMean, snrPeak, freqMin, freqMean, freqMax, freqPeak, wave]
Index: []

--------------------------->INJECTION TYPE:  ga_20
maximum amplitude INJECTION parameters:

,amplitude,dec,duration,pol,ra,seed,time,time_at_H1,time_at_L1
ga_20,2.715934686207109e-20,1.1738824812375608,0.02,4.792634243939587,0.17177319496836016,5533.0,1402335239.2306128,1402335239.2119095,1402335239.2177355

IFO: H , TRIGGERS: 0 found in a time window of  5 s around the maximum amplitude injection of type ga_20
TRIGGER parameters:

Empty DataFrame
Columns: [gps, gpsPeak, duration, EnWDF, snrMean, snrPeak, freqMin, freqMean, freqMax, freqPeak, wave]
Index: []

IFO: L , TRIGGERS: 0 found in a time window of  5 s around the maximum amplitude injection of type ga_20
TRIGGER parameters:

Empty DataFrame
Columns: [gps, gpsPeak, duration, EnWDF, snrMean, snrPeak, freqMin, freqMean, freqMax, freqPeak, wave]
Index: []

--------------------------->INJECTION TYPE:  cs_kink
maximum amplitude INJECTION parameters:

,amplitude,dec,frequency,pol,ra,seed,time,time_at_H1,time_at_L1
cs_kink,1.378042182364688e-20,0.44122903966842403,66.21960418074819,0.5390549453996212,1.0775816309143555,5533.0,1402234274.47748,1402234274.4679492,1402234274.461881

IFO: H , TRIGGERS: 0 found in a time window of  5 s around the maximum amplitude injection of type cs_kink
TRIGGER parameters:

Empty DataFrame
Columns: [gps, gpsPeak, duration, EnWDF, snrMean, snrPeak, freqMin, freqMean, freqMax, freqPeak, wave]
Index: []

IFO: L , TRIGGERS: 0 found in a time window of  5 s around the maximum amplitude injection of type cs_kink
TRIGGER parameters:

Empty DataFrame
Columns: [gps, gpsPeak, duration, EnWDF, snrMean, snrPeak, freqMin, freqMean, freqMax, freqPeak, wave]
Index: []

--------------------------->INJECTION TYPE:  cs_cusp
maximum amplitude INJECTION parameters:

,amplitude,dec,frequency,pol,ra,seed,time,time_at_H1,time_at_L1
cs_cusp,3.940102101531899e-21,0.3920438018803519,54.052852938611736,2.0010551018361125,5.693881942900467,5533.0,1402355184.5462062,1402355184.5533626,1402355184.558654

IFO: H , TRIGGERS: 1 found in a time window of  5 s around the maximum amplitude injection of type cs_cusp
trigger number: 6621 , delay from inj: 3.4476139545440674 s
TRIGGER parameters:

,gps,gpsPeak,duration,EnWDF,snrMean,snrPeak,freqMin,freqMean,freqMax,freqPeak,wave
6621,1402355187.9140625,1402355188.0009766,0.0478515625,1.1409933461905022,1.0270445003129365,11.951025510614738,16.0,83.38461538461539,180.0,20.0,BsplineC309

IFO: L , TRIGGERS: 0 found in a time window of  5 s around the maximum amplitude injection of type cs_cusp
TRIGGER parameters:

Empty DataFrame
Columns: [gps, gpsPeak, duration, EnWDF, snrMean, snrPeak, freqMin, freqMean, freqMax, freqPeak, wave]
Index: []

--------------------------->INJECTION TYPE:  sg_2634q700
maximum amplitude INJECTION parameters:

,amplitude,dec,eccentricity,frequency,phase,pol,quality,ra,seed,time,time_at_H1,time_at_L1
sg_2634q700,9.480412878039765e-22,-0.6840156305697268,0.18114285711305456,2634.0,1.4472374491923778,3.022047259176804,700.0,5.670223887679522,5533.0,1402467354.0733016,1402467354.0822747,1402467354.0725088

IFO: H , TRIGGERS: 0 found in a time window of  5 s around the maximum amplitude injection of type sg_2634q700
TRIGGER parameters:

Empty DataFrame
Columns: [gps, gpsPeak, duration, EnWDF, snrMean, snrPeak, freqMin, freqMean, freqMax, freqPeak, wave]
Index: []

IFO: L , TRIGGERS: 0 found in a time window of  5 s around the maximum amplitude injection of type sg_2634q700
TRIGGER parameters:

Empty DataFrame
Columns: [gps, gpsPeak, duration, EnWDF, snrMean, snrPeak, freqMin, freqMean, freqMax, freqPeak, wave]
Index: []

--------------------------->INJECTION TYPE:  sg_40q700
maximum amplitude INJECTION parameters:

,amplitude,dec,eccentricity,frequency,phase,pol,quality,ra,seed,time,time_at_H1,time_at_L1
sg_40q700,6.366350669500847e-22,-1.3350136852276044,0.9180230298117099,40.0,2.9487643623373945,5.182574393705374,700.0,3.1227082323941704,5533.0,1402392655.7826188,1402392655.7985713,1402392655.7961648

IFO: H , TRIGGERS: 0 found in a time window of  5 s around the maximum amplitude injection of type sg_40q700
TRIGGER parameters:

Empty DataFrame
Columns: [gps, gpsPeak, duration, EnWDF, snrMean, snrPeak, freqMin, freqMean, freqMax, freqPeak, wave]
Index: []

IFO: L , TRIGGERS: 0 found in a time window of  5 s around the maximum amplitude injection of type sg_40q700
TRIGGER parameters:

Empty DataFrame
Columns: [gps, gpsPeak, duration, EnWDF, snrMean, snrPeak, freqMin, freqMean, freqMax, freqPeak, wave]
Index: []

--------------------------->INJECTION TYPE:  sg_25q9
maximum amplitude INJECTION parameters:

,amplitude,dec,eccentricity,frequency,phase,pol,quality,ra,seed,time,time_at_H1,time_at_L1
sg_25q9,6.133673856855417e-22,-1.4964449369380357,0.24969628806175037,25.0,5.855923878741789,1.9244561899587653,9.0,5.072683717089373,5533.0,1402228618.7689893,1402228618.7833517,1402228618.7790143

IFO: H , TRIGGERS: 0 found in a time window of  5 s around the maximum amplitude injection of type sg_25q9
TRIGGER parameters:

Empty DataFrame
Columns: [gps, gpsPeak, duration, EnWDF, snrMean, snrPeak, freqMin, freqMean, freqMax, freqPeak, wave]
Index: []

IFO: L , TRIGGERS: 0 found in a time window of  5 s around the maximum amplitude injection of type sg_25q9
TRIGGER parameters:

Empty DataFrame
Columns: [gps, gpsPeak, duration, EnWDF, snrMean, snrPeak, freqMin, freqMean, freqMax, freqPeak, wave]
Index: []

--------------------------->INJECTION TYPE:  sg_3067q3
maximum amplitude INJECTION parameters:

,amplitude,dec,eccentricity,frequency,phase,pol,quality,ra,seed,time,time_at_H1,time_at_L1
sg_3067q3,4.554605597190681e-22,0.6712545110200676,0.020723613558987886,3067.0,4.3275553342302,4.552056945746155,3.0,3.668106721286079,5533.0,1402368458.339731,1402368458.3197527,1402368458.318716

IFO: H , TRIGGERS: 0 found in a time window of  5 s around the maximum amplitude injection of type sg_3067q3
TRIGGER parameters:

Empty DataFrame
Columns: [gps, gpsPeak, duration, EnWDF, snrMean, snrPeak, freqMin, freqMean, freqMax, freqPeak, wave]
Index: []

IFO: L , TRIGGERS: 1 found in a time window of  5 s around the maximum amplitude injection of type sg_3067q3
trigger number: 10022 , delay from inj: 4.318227767944336 s
TRIGGER parameters:

,gps,gpsPeak,duration,EnWDF,snrMean,snrPeak,freqMin,freqMean,freqMax,freqPeak,wave
10022,1402368453.8125,1402368454.0004883,0.0029296875,3.1408955487457297,3.046846813822954,39.08248268187187,4.0,65.53846153846153,116.0,44.0,BsplineC206

--------------------------->INJECTION TYPE:  sg_2477q9
maximum amplitude INJECTION parameters:

,amplitude,dec,eccentricity,frequency,phase,pol,quality,ra,seed,time,time_at_H1,time_at_L1
sg_2477q9,3.8923840594274957e-22,0.003397456909661263,0.4495046596734471,2477.0,2.6114595299479113,0.14685376164755834,9.0,4.256640691477506,5533.0,1402437789.9640288,1402437789.973194,1402437789.9672549

IFO: H , TRIGGERS: 0 found in a time window of  5 s around the maximum amplitude injection of type sg_2477q9
TRIGGER parameters:

Empty DataFrame
Columns: [gps, gpsPeak, duration, EnWDF, snrMean, snrPeak, freqMin, freqMean, freqMax, freqPeak, wave]
Index: []

IFO: L , TRIGGERS: 0 found in a time window of  5 s around the maximum amplitude injection of type sg_2477q9
TRIGGER parameters:

Empty DataFrame
Columns: [gps, gpsPeak, duration, EnWDF, snrMean, snrPeak, freqMin, freqMean, freqMax, freqPeak, wave]
Index: []

--------------------------->INJECTION TYPE:  sg_32q3
maximum amplitude INJECTION parameters:

,amplitude,dec,eccentricity,frequency,phase,pol,quality,ra,seed,time,time_at_H1,time_at_L1
sg_32q3,3.645367020854758e-22,0.49866568318269777,0.8974013339680668,32.0,3.8583193289290976,4.956842665987593,3.0,0.42271915180426844,5533.0,1402449186.347268,1402449186.349572,1402449186.3578162

IFO: H , TRIGGERS: 1 found in a time window of  5 s around the maximum amplitude injection of type sg_32q3
trigger number: 608 , delay from inj: 3.650428056716919 s
TRIGGER parameters:

,gps,gpsPeak,duration,EnWDF,snrMean,snrPeak,freqMin,freqMean,freqMax,freqPeak,wave
608,1402449189.984375,1402449190.0,0.00390625,1.3320532213488885,1.3925616250842514,18.183097895979976,12.0,62.0,112.0,20.0,BsplineC206

IFO: L , TRIGGERS: 0 found in a time window of  5 s around the maximum amplitude injection of type sg_32q3
TRIGGER parameters:

Empty DataFrame
Columns: [gps, gpsPeak, duration, EnWDF, snrMean, snrPeak, freqMin, freqMean, freqMax, freqPeak, wave]
Index: []

--------------------------->INJECTION TYPE:  sg_612q700
maximum amplitude INJECTION parameters:

,amplitude,dec,eccentricity,frequency,phase,pol,quality,ra,seed,time,time_at_H1,time_at_L1
sg_612q700,3.137520908645889e-22,0.19271745912367538,0.20623597773045477,612.0,3.8934547536135278,2.2419504423757455,700.0,3.6415097812086534,5533.0,1402401889.4632783,1402401889.4667394,1402401889.4759598

IFO: H , TRIGGERS: 0 found in a time window of  5 s around the maximum amplitude injection of type sg_612q700
TRIGGER parameters:

Empty DataFrame
Columns: [gps, gpsPeak, duration, EnWDF, snrMean, snrPeak, freqMin, freqMean, freqMax, freqPeak, wave]
Index: []

IFO: L , TRIGGERS: 0 found in a time window of  5 s around the maximum amplitude injection of type sg_612q700
TRIGGER parameters:

Empty DataFrame
Columns: [gps, gpsPeak, duration, EnWDF, snrMean, snrPeak, freqMin, freqMean, freqMax, freqPeak, wave]
Index: []

--------------------------->INJECTION TYPE:  sg_196q700
maximum amplitude INJECTION parameters:

,amplitude,dec,eccentricity,frequency,phase,pol,quality,ra,seed,time,time_at_H1,time_at_L1
sg_196q700,2.8997781931350107e-22,0.48774540811861805,0.2229929378301294,196.0,5.473694134605215,5.94005169018807,700.0,5.946839158061042,5533.0,1402288910.165599,1402288910.16635,1402288910.163127

IFO: H , TRIGGERS: 0 found in a time window of  5 s around the maximum amplitude injection of type sg_196q700
TRIGGER parameters:

Empty DataFrame
Columns: [gps, gpsPeak, duration, EnWDF, snrMean, snrPeak, freqMin, freqMean, freqMax, freqPeak, wave]
Index: []

IFO: L , TRIGGERS: 0 found in a time window of  5 s around the maximum amplitude injection of type sg_196q700
TRIGGER parameters:

Empty DataFrame
Columns: [gps, gpsPeak, duration, EnWDF, snrMean, snrPeak, freqMin, freqMean, freqMax, freqPeak, wave]
Index: []

--------------------------->INJECTION TYPE:  ga_3
maximum amplitude INJECTION parameters:

,amplitude,dec,duration,pol,ra,seed,time,time_at_H1,time_at_L1
ga_3,2.887139490407032e-22,0.7982272915261704,0.003,1.6183439788231966,0.26171958426613195,5533.0,1402485774.624565,1402485774.6083755,1402485774.6058788

IFO: H , TRIGGERS: 0 found in a time window of  5 s around the maximum amplitude injection of type ga_3
TRIGGER parameters:

Empty DataFrame
Columns: [gps, gpsPeak, duration, EnWDF, snrMean, snrPeak, freqMin, freqMean, freqMax, freqPeak, wave]
Index: []

IFO: L , TRIGGERS: 0 found in a time window of  5 s around the maximum amplitude injection of type ga_3
TRIGGER parameters:

Empty DataFrame
Columns: [gps, gpsPeak, duration, EnWDF, snrMean, snrPeak, freqMin, freqMean, freqMax, freqPeak, wave]
Index: []

--------------------------->INJECTION TYPE:  sg_2000q3
maximum amplitude INJECTION parameters:

,amplitude,dec,eccentricity,frequency,phase,pol,quality,ra,seed,time,time_at_H1,time_at_L1
sg_2000q3,2.726781301433983e-22,-0.9810458849732968,0.889590759808271,2000.0,5.0334405669889755,1.7051641412799707,3.0,3.07704156951787,5533.0,1402404290.8317468,1402404290.8521101,1402404290.850798

IFO: H , TRIGGERS: 0 found in a time window of  5 s around the maximum amplitude injection of type sg_2000q3
TRIGGER parameters:

Empty DataFrame
Columns: [gps, gpsPeak, duration, EnWDF, snrMean, snrPeak, freqMin, freqMean, freqMax, freqPeak, wave]
Index: []

IFO: L , TRIGGERS: 0 found in a time window of  5 s around the maximum amplitude injection of type sg_2000q3
TRIGGER parameters:

Empty DataFrame
Columns: [gps, gpsPeak, duration, EnWDF, snrMean, snrPeak, freqMin, freqMean, freqMax, freqPeak, wave]
Index: []

--------------------------->INJECTION TYPE:  sg_1615q100
maximum amplitude INJECTION parameters:

,amplitude,dec,eccentricity,frequency,phase,pol,quality,ra,seed,time,time_at_H1,time_at_L1
sg_1615q100,2.389017234635017e-22,0.09664687874925225,0.3550333373247231,1615.0,1.2888127388812731,3.353949462845663,100.0,2.3490392267225726,5533.0,1402515564.3214457,1402515564.311507,1402515564.3040059

IFO: H , TRIGGERS: 0 found in a time window of  5 s around the maximum amplitude injection of type sg_1615q100
TRIGGER parameters:

Empty DataFrame
Columns: [gps, gpsPeak, duration, EnWDF, snrMean, snrPeak, freqMin, freqMean, freqMax, freqPeak, wave]
Index: []

IFO: L , TRIGGERS: 1 found in a time window of  5 s around the maximum amplitude injection of type sg_1615q100
trigger number: 5679 , delay from inj: 3.3040058612823486 s
TRIGGER parameters:

,gps,gpsPeak,duration,EnWDF,snrMean,snrPeak,freqMin,freqMean,freqMax,freqPeak,wave
5679,1402515560.9140625,1402515561.0,0.00244140625,0.5848925728955924,0.7946973809086287,13.995979670323992,204.0,296.15384615384613,392.0,348.0,BsplineC103

--------------------------->INJECTION TYPE:  sg_70q100
maximum amplitude INJECTION parameters:

,amplitude,dec,eccentricity,frequency,phase,pol,quality,ra,seed,time,time_at_H1,time_at_L1
sg_70q100,1.946220163787844e-22,-0.8932180480009073,0.5839839865728583,70.0,2.130362693405128,1.572226626853752,100.0,2.0358277687844057,5533.0,1402319758.5072904,1402319758.52573,1402319758.518867

IFO: H , TRIGGERS: 0 found in a time window of  5 s around the maximum amplitude injection of type sg_70q100
TRIGGER parameters:

Empty DataFrame
Columns: [gps, gpsPeak, duration, EnWDF, snrMean, snrPeak, freqMin, freqMean, freqMax, freqPeak, wave]
Index: []

IFO: L , TRIGGERS: 2 found in a time window of  5 s around the maximum amplitude injection of type sg_70q100
trigger number: 699 , delay from inj: 0.19415998458862305 s
trigger number: 700 , delay from inj: 3.165703296661377 s
TRIGGER parameters:

,gps,gpsPeak,duration,EnWDF,snrMean,snrPeak,freqMin,freqMean,freqMax,freqPeak,wave
699,1402319758.125,1402319758.324707,0.2177734375,0.535614108558764,0.2453604245392406,1.1175331819779115,56.0,148.0,280.0,72.0,BsplineC309
700,1402319761.515625,1402319761.6845703,0.2021484375,0.5447616082039239,0.250677224257248,1.144218621086384,36.0,132.92307692307693,252.0,204.0,BsplineC309

--------------------------->INJECTION TYPE:  sg_1304q9
maximum amplitude INJECTION parameters:

,amplitude,dec,eccentricity,frequency,phase,pol,quality,ra,seed,time,time_at_H1,time_at_L1
sg_1304q9,1.9203389711001778e-22,0.5584377359486942,0.2919813443547997,1304.0,2.7031798782876866,2.228826909218597,9.0,6.082025723197098,5533.0,1402337749.7404492,1402337749.7277656,1402337749.736696

IFO: H , TRIGGERS: 0 found in a time window of  5 s around the maximum amplitude injection of type sg_1304q9
TRIGGER parameters:

Empty DataFrame
Columns: [gps, gpsPeak, duration, EnWDF, snrMean, snrPeak, freqMin, freqMean, freqMax, freqPeak, wave]
Index: []

IFO: L , TRIGGERS: 0 found in a time window of  5 s around the maximum amplitude injection of type sg_1304q9
TRIGGER parameters:

Empty DataFrame
Columns: [gps, gpsPeak, duration, EnWDF, snrMean, snrPeak, freqMin, freqMean, freqMax, freqPeak, wave]
Index: []

--------------------------->INJECTION TYPE:  sg_70q3
maximum amplitude INJECTION parameters:

,amplitude,dec,eccentricity,frequency,phase,pol,quality,ra,seed,time,time_at_H1,time_at_L1
sg_70q3,1.4946436577723127e-22,1.2587606002758203,0.175763303797297,70.0,1.4532521080282115,1.4748933488343836,3.0,2.4129233495308116,5533.0,1402353639.8558695,1402353639.8369079,1402353639.8401675

IFO: H , TRIGGERS: 1 found in a time window of  5 s around the maximum amplitude injection of type sg_70q3
trigger number: 6520 , delay from inj: 1.8364195823669434 s
TRIGGER parameters:

,gps,gpsPeak,duration,EnWDF,snrMean,snrPeak,freqMin,freqMean,freqMax,freqPeak,wave
6520,1402353637.9140625,1402353638.0004883,0.00390625,1.4433353221440155,1.3876075237634444,16.98823627254056,4.0,59.38461538461539,136.0,20.0,BsplineC309

IFO: L , TRIGGERS: 0 found in a time window of  5 s around the maximum amplitude injection of type sg_70q3
TRIGGER parameters:

Empty DataFrame
Columns: [gps, gpsPeak, duration, EnWDF, snrMean, snrPeak, freqMin, freqMean, freqMax, freqPeak, wave]
Index: []

--------------------------->INJECTION TYPE:  ga_1
maximum amplitude INJECTION parameters:

,amplitude,dec,duration,pol,ra,seed,time,time_at_H1,time_at_L1
ga_1,1.4710680826071645e-22,-1.3304068171871026,0.001,5.6252797285300735,3.2877168597827255,5533.0,1402360912.5626009,1402360912.5746262,1402360912.5687046

IFO: H , TRIGGERS: 0 found in a time window of  5 s around the maximum amplitude injection of type ga_1
TRIGGER parameters:

Empty DataFrame
Columns: [gps, gpsPeak, duration, EnWDF, snrMean, snrPeak, freqMin, freqMean, freqMax, freqPeak, wave]
Index: []

IFO: L , TRIGGERS: 0 found in a time window of  5 s around the maximum amplitude injection of type ga_1
TRIGGER parameters:

Empty DataFrame
Columns: [gps, gpsPeak, duration, EnWDF, snrMean, snrPeak, freqMin, freqMean, freqMax, freqPeak, wave]
Index: []

--------------------------->INJECTION TYPE:  sg_70q9
maximum amplitude INJECTION parameters:

,amplitude,dec,eccentricity,frequency,phase,pol,quality,ra,seed,time,time_at_H1,time_at_L1
sg_70q9,1.465197882524215e-22,-0.40053275770953783,0.21263023628941813,70.0,1.9180604762203064,2.196910748035797,9.0,4.231468011585244,5533.0,1402289119.196487,1402289119.1905987,1402289119.1837962

IFO: H , TRIGGERS: 0 found in a time window of  5 s around the maximum amplitude injection of type sg_70q9
TRIGGER parameters:

Empty DataFrame
Columns: [gps, gpsPeak, duration, EnWDF, snrMean, snrPeak, freqMin, freqMean, freqMax, freqPeak, wave]
Index: []

IFO: L , TRIGGERS: 0 found in a time window of  5 s around the maximum amplitude injection of type sg_70q9
TRIGGER parameters:

Empty DataFrame
Columns: [gps, gpsPeak, duration, EnWDF, snrMean, snrPeak, freqMin, freqMean, freqMax, freqPeak, wave]
Index: []

--------------------------->INJECTION TYPE:  sg_849q3
maximum amplitude INJECTION parameters:

,amplitude,dec,eccentricity,frequency,phase,pol,quality,ra,seed,time,time_at_H1,time_at_L1
sg_849q3,1.4199181372409474e-22,1.2480379881348327,0.42131212203310786,849.0,4.343803058647803,4.031316656310328,3.0,0.6530290691060283,5533.0,1402353926.7381709,1402353926.7233908,1402353926.7305055

IFO: H , TRIGGERS: 0 found in a time window of  5 s around the maximum amplitude injection of type sg_849q3
TRIGGER parameters:

Empty DataFrame
Columns: [gps, gpsPeak, duration, EnWDF, snrMean, snrPeak, freqMin, freqMean, freqMax, freqPeak, wave]
Index: []

IFO: L , TRIGGERS: 0 found in a time window of  5 s around the maximum amplitude injection of type sg_849q3
TRIGGER parameters:

Empty DataFrame
Columns: [gps, gpsPeak, duration, EnWDF, snrMean, snrPeak, freqMin, freqMean, freqMax, freqPeak, wave]
Index: []

--------------------------->INJECTION TYPE:  sg_554q9
maximum amplitude INJECTION parameters:

,amplitude,dec,eccentricity,frequency,phase,pol,quality,ra,seed,time,time_at_H1,time_at_L1
sg_554q9,1.2998710059788908e-22,0.006182755448108294,0.4609107269085143,554.0,5.009407377562052,3.4745288751899137,9.0,3.9994981745977998,5533.0,1402416364.5936322,1402416364.6069853,1402416364.611832

IFO: H , TRIGGERS: 0 found in a time window of  5 s around the maximum amplitude injection of type sg_554q9
TRIGGER parameters:

Empty DataFrame
Columns: [gps, gpsPeak, duration, EnWDF, snrMean, snrPeak, freqMin, freqMean, freqMax, freqPeak, wave]
Index: []

IFO: L , TRIGGERS: 0 found in a time window of  5 s around the maximum amplitude injection of type sg_554q9
TRIGGER parameters:

Empty DataFrame
Columns: [gps, gpsPeak, duration, EnWDF, snrMean, snrPeak, freqMin, freqMean, freqMax, freqPeak, wave]
Index: []

--------------------------->INJECTION TYPE:  sg_235q100
maximum amplitude INJECTION parameters:

,amplitude,dec,eccentricity,frequency,phase,pol,quality,ra,seed,time,time_at_H1,time_at_L1
sg_235q100,1.1934478311520949e-22,-0.03543894088604365,0.6194327152157147,235.0,4.997280041065855,5.737673874659232,100.0,4.941288920927737,5533.0,1402391448.4242349,1402391448.4101114,1402391448.4082754

IFO: H , TRIGGERS: 1 found in a time window of  5 s around the maximum amplitude injection of type sg_235q100
trigger number: 8971 , delay from inj: 1.409623146057129 s
TRIGGER parameters:

,gps,gpsPeak,duration,EnWDF,snrMean,snrPeak,freqMin,freqMean,freqMax,freqPeak,wave
8971,1402391446.828125,1402391447.0004883,0.00439453125,1.6000049359587631,1.4662087255340386,18.40320011983402,12.0,62.0,112.0,20.0,BsplineC206

IFO: L , TRIGGERS: 0 found in a time window of  5 s around the maximum amplitude injection of type sg_235q100
TRIGGER parameters:

Empty DataFrame
Columns: [gps, gpsPeak, duration, EnWDF, snrMean, snrPeak, freqMin, freqMean, freqMax, freqPeak, wave]
Index: []

--------------------------->INJECTION TYPE:  sg_235q9
maximum amplitude INJECTION parameters:

,amplitude,dec,eccentricity,frequency,phase,pol,quality,ra,seed,time,time_at_H1,time_at_L1
sg_235q9,1.0638789303442182e-22,-0.7185348574173458,0.008169273664449639,235.0,0.31505881820306014,5.4869336065417835,9.0,2.360900027111682,5533.0,1402377661.1708722,1402377661.1806865,1402377661.1842492

IFO: H , TRIGGERS: 1 found in a time window of  5 s around the maximum amplitude injection of type sg_235q9
trigger number: 8268 , delay from inj: 4.1801981925964355 s
TRIGGER parameters:

,gps,gpsPeak,duration,EnWDF,snrMean,snrPeak,freqMin,freqMean,freqMax,freqPeak,wave
8268,1402377656.9140625,1402377657.0004883,0.00439453125,1.1265120248681837,1.1801805053583403,15.081171394118993,4.0,59.53846153846154,136.0,20.0,BsplineC309

IFO: L , TRIGGERS: 0 found in a time window of  5 s around the maximum amplitude injection of type sg_235q9
TRIGGER parameters:

Empty DataFrame
Columns: [gps, gpsPeak, duration, EnWDF, snrMean, snrPeak, freqMin, freqMean, freqMax, freqPeak, wave]
Index: []

--------------------------->INJECTION TYPE:  sg_235q3
maximum amplitude INJECTION parameters:

,amplitude,dec,eccentricity,frequency,phase,pol,quality,ra,seed,time,time_at_H1,time_at_L1
sg_235q3,1.027413161020615e-22,1.4394101635071137,0.3546234013893249,235.0,0.3303103882074489,2.1283361396906253,3.0,0.9367114062426499,5533.0,1402438840.0977094,1402438840.0817056,1402438840.0872295

IFO: H , TRIGGERS: 0 found in a time window of  5 s around the maximum amplitude injection of type sg_235q3
TRIGGER parameters:

Empty DataFrame
Columns: [gps, gpsPeak, duration, EnWDF, snrMean, snrPeak, freqMin, freqMean, freqMax, freqPeak, wave]
Index: []

IFO: L , TRIGGERS: 1 found in a time window of  5 s around the maximum amplitude injection of type sg_235q3
trigger number: 2911 , delay from inj: 1.0872294902801514 s
TRIGGER parameters:

,gps,gpsPeak,duration,EnWDF,snrMean,snrPeak,freqMin,freqMean,freqMax,freqPeak,wave
2911,1402438838.828125,1402438839.0,0.0029296875,1.9582943883801585,1.562839786868523,25.68126263009555,148.0,198.15384615384616,252.0,188.0,BsplineC206

--------------------------->INJECTION TYPE:  wnb_1600_1700_t2000
maximum amplitude INJECTION parameters:

,amplitude,bandwidth,dec,duration,eccentricity,frequency,phase,pol,ra,seed,time,time_at_H1,time_at_L1
wnb_1600_1700_t2000,2.409952363954592e-34,100.0,-0.13578954393407108,2.0,0.5394345224821376,1650.0,5.217842306379156,2.8455030251438957,4.8599667129122,5533.0,1402206558.2491162,1402206558.241756,1402206558.2336032

IFO: H , TRIGGERS: 1 found in a time window of  5 s around the maximum amplitude injection of type wnb_1600_1700_t2000
trigger number: 10066 , delay from inj: 0.7587323188781738 s
TRIGGER parameters:

,gps,gpsPeak,duration,EnWDF,snrMean,snrPeak,freqMin,freqMean,freqMax,freqPeak,wave
10066,1402206558.875,1402206559.0004883,0.0146484375,0.8942158938004016,0.9489170095667444,11.33054275514916,32.0,82.76923076923077,144.0,44.0,BsplineC206

IFO: L , TRIGGERS: 1 found in a time window of  5 s around the maximum amplitude injection of type wnb_1600_1700_t2000
trigger number: 6460 , delay from inj: 1.7673733234405518 s
TRIGGER parameters:

,gps,gpsPeak,duration,EnWDF,snrMean,snrPeak,freqMin,freqMean,freqMax,freqPeak,wave
6460,1402206559.7890625,1402206560.0009766,0.01708984375,0.694797546233576,0.6208425974937827,6.3099233978064575,4.0,58.15384615384615,160.0,20.0,BsplineC309

--------------------------->INJECTION TYPE:  wnb_1220_1520_t500
maximum amplitude INJECTION parameters:

,amplitude,bandwidth,dec,duration,eccentricity,frequency,phase,pol,ra,seed,time,time_at_H1,time_at_L1
wnb_1220_1520_t500,6.378558632907808e-35,300.0,1.3918171972943447,0.5,0.6415628276200178,1370.0,5.5602434267526,3.494904360274674,1.003318495867917,5533.0,1402239805.5893328,1402239805.5725412,1402239805.5757031

IFO: H , TRIGGERS: 1 found in a time window of  5 s around the maximum amplitude injection of type wnb_1220_1520_t500
trigger number: 11908 , delay from inj: 3.4279470443725586 s
TRIGGER parameters:

,gps,gpsPeak,duration,EnWDF,snrMean,snrPeak,freqMin,freqMean,freqMax,freqPeak,wave
11908,1402239808.796875,1402239809.0004883,0.0126953125,0.90475191763146,0.898935044704384,10.81726817525236,12.0,70.3076923076923,180.0,44.0,BsplineC206

IFO: L , TRIGGERS: 1 found in a time window of  5 s around the maximum amplitude injection of type wnb_1220_1520_t500
trigger number: 10697 , delay from inj: 1.5757031440734863 s
TRIGGER parameters:

,gps,gpsPeak,duration,EnWDF,snrMean,snrPeak,freqMin,freqMean,freqMax,freqPeak,wave
10697,1402239803.8046875,1402239804.0,0.14404296875,0.9024711163833092,0.6602475253894027,10.793356099677576,140.0,195.23076923076923,280.0,180.0,BsplineC206

--------------------------->INJECTION TYPE:  wnb_995_1005_t1000
maximum amplitude INJECTION parameters:

,amplitude,bandwidth,dec,duration,eccentricity,frequency,phase,pol,ra,seed,time,time_at_H1,time_at_L1
wnb_995_1005_t1000,1.5884527374874643e-35,10.0,-1.1265066542899445,1.0,0.039834961978462036,1000.0,2.996292963969211,2.64529178283408,3.721839912219038,5533.0,1402219840.6211474,1402219840.6329637,1402219840.6321974

IFO: H , TRIGGERS: 0 found in a time window of  5 s around the maximum amplitude injection of type wnb_995_1005_t1000
TRIGGER parameters:

Empty DataFrame
Columns: [gps, gpsPeak, duration, EnWDF, snrMean, snrPeak, freqMin, freqMean, freqMax, freqPeak, wave]
Index: []

IFO: L , TRIGGERS: 0 found in a time window of  5 s around the maximum amplitude injection of type wnb_995_1005_t1000
TRIGGER parameters:

Empty DataFrame
Columns: [gps, gpsPeak, duration, EnWDF, snrMean, snrPeak, freqMin, freqMean, freqMax, freqPeak, wave]
Index: []

--------------------------->INJECTION TYPE:  wnb_1395_1405_t100
maximum amplitude INJECTION parameters:

,amplitude,bandwidth,dec,duration,eccentricity,frequency,phase,pol,ra,seed,time,time_at_H1,time_at_L1
wnb_1395_1405_t100,6.879192123620501e-36,10.0,-0.6255313994495769,0.1,0.9645047791821774,1400.0,2.3455110248553486,1.2809551080770805,4.616725682691891,5533.0,1402507605.832664,1402507605.8510518,1402507605.8536344

IFO: H , TRIGGERS: 0 found in a time window of  5 s around the maximum amplitude injection of type wnb_1395_1405_t100
TRIGGER parameters:

Empty DataFrame
Columns: [gps, gpsPeak, duration, EnWDF, snrMean, snrPeak, freqMin, freqMean, freqMax, freqPeak, wave]
Index: []

IFO: L , TRIGGERS: 0 found in a time window of  5 s around the maximum amplitude injection of type wnb_1395_1405_t100
TRIGGER parameters:

Empty DataFrame
Columns: [gps, gpsPeak, duration, EnWDF, snrMean, snrPeak, freqMin, freqMean, freqMax, freqPeak, wave]
Index: []

--------------------------->INJECTION TYPE:  wnb_800_1000_t10
maximum amplitude INJECTION parameters:

,amplitude,bandwidth,dec,duration,eccentricity,frequency,phase,pol,ra,seed,time,time_at_H1,time_at_L1
wnb_800_1000_t10,1.1094602486912695e-36,200.0,1.0378489591378561,0.01,0.4957653494097891,900.0,4.182799378412639,4.444968469244686,1.0589362172703265,5533.0,1402350956.880693,1402350956.8628356,1402350956.8698392

IFO: H , TRIGGERS: 0 found in a time window of  5 s around the maximum amplitude injection of type wnb_800_1000_t10
TRIGGER parameters:

Empty DataFrame
Columns: [gps, gpsPeak, duration, EnWDF, snrMean, snrPeak, freqMin, freqMean, freqMax, freqPeak, wave]
Index: []

IFO: L , TRIGGERS: 0 found in a time window of  5 s around the maximum amplitude injection of type wnb_800_1000_t10
TRIGGER parameters:

Empty DataFrame
Columns: [gps, gpsPeak, duration, EnWDF, snrMean, snrPeak, freqMin, freqMean, freqMax, freqPeak, wave]
Index: []

--------------------------->INJECTION TYPE:  wnb_750_850_t100
maximum amplitude INJECTION parameters:

,amplitude,bandwidth,dec,duration,eccentricity,frequency,phase,pol,ra,seed,time,time_at_H1,time_at_L1
wnb_750_850_t100,1.0766345292885812e-36,100.0,-0.6648383711603701,0.1,0.11226566654657422,800.0,1.5466341401942587,6.061323066391147,4.686756021847648,5533.0,1402284521.8444858,1402284521.8507466,1402284521.8409636

IFO: H , TRIGGERS: 1 found in a time window of  5 s around the maximum amplitude injection of type wnb_750_850_t100
trigger number: 3758 , delay from inj: 2.1497416496276855 s
TRIGGER parameters:

,gps,gpsPeak,duration,EnWDF,snrMean,snrPeak,freqMin,freqMean,freqMax,freqPeak,wave
3758,1402284523.9453125,1402284524.0004883,0.00927734375,1.1983644884142903,1.4137450151223747,16.64321275006325,8.0,72.3076923076923,140.0,68.0,BsplineC309

IFO: L , TRIGGERS: 0 found in a time window of  5 s around the maximum amplitude injection of type wnb_750_850_t100
TRIGGER parameters:

Empty DataFrame
Columns: [gps, gpsPeak, duration, EnWDF, snrMean, snrPeak, freqMin, freqMean, freqMax, freqPeak, wave]
Index: []

--------------------------->INJECTION TYPE:  wnb_250_350_t800
maximum amplitude INJECTION parameters:

,amplitude,bandwidth,dec,duration,eccentricity,frequency,phase,pol,ra,seed,time,time_at_H1,time_at_L1
wnb_250_350_t800,4.543039472454408e-37,100.0,-0.4908328075145552,0.8,0.1115327357938406,300.0,5.995668711207308,2.3967867905339717,5.188489318282579,5533.0,1402474443.4133298,1402474443.4092517,1402474443.4022293

IFO: H , TRIGGERS: 1 found in a time window of  5 s around the maximum amplitude injection of type wnb_250_350_t800
trigger number: 1799 , delay from inj: 3.4087634086608887 s
TRIGGER parameters:

,gps,gpsPeak,duration,EnWDF,snrMean,snrPeak,freqMin,freqMean,freqMax,freqPeak,wave
1799,1402474439.96875,1402474440.0004883,0.0048828125,1.454865847955452,1.5315385432910151,18.418249238592587,8.0,61.69230769230769,112.0,8.0,BsplineC206

IFO: L , TRIGGERS: 0 found in a time window of  5 s around the maximum amplitude injection of type wnb_250_350_t800
TRIGGER parameters:

Empty DataFrame
Columns: [gps, gpsPeak, duration, EnWDF, snrMean, snrPeak, freqMin, freqMean, freqMax, freqPeak, wave]
Index: []

--------------------------->INJECTION TYPE:  wnb_400_450_t300
maximum amplitude INJECTION parameters:

,amplitude,bandwidth,dec,duration,eccentricity,frequency,phase,pol,ra,seed,time,time_at_H1,time_at_L1
wnb_400_450_t300,2.9562247963907372e-37,50.0,0.06748415830304533,0.3,0.6422955952771118,425.0,5.423118968065654,5.597107951670528,2.197470467302672,5533.0,1402294677.4789786,1402294677.483233,1402294677.4922254

IFO: H , TRIGGERS: 1 found in a time window of  5 s around the maximum amplitude injection of type wnb_400_450_t300
trigger number: 4247 , delay from inj: 3.4827446937561035 s
TRIGGER parameters:

,gps,gpsPeak,duration,EnWDF,snrMean,snrPeak,freqMin,freqMean,freqMax,freqPeak,wave
4247,1402294673.78125,1402294674.0004883,0.005859375,1.1201774115376035,1.0765174402679505,12.033258979409617,8.0,62.0,120.0,8.0,BsplineC206

IFO: L , TRIGGERS: 0 found in a time window of  5 s around the maximum amplitude injection of type wnb_400_450_t300
TRIGGER parameters:

Empty DataFrame
Columns: [gps, gpsPeak, duration, EnWDF, snrMean, snrPeak, freqMin, freqMean, freqMax, freqPeak, wave]
Index: []

--------------------------->INJECTION TYPE:  wnb_250_350_t100
maximum amplitude INJECTION parameters:

,amplitude,bandwidth,dec,duration,eccentricity,frequency,phase,pol,ra,seed,time,time_at_H1,time_at_L1
wnb_250_350_t100,2.7877256571769102e-37,100.0,0.41379677066567416,0.1,0.38311541360511736,300.0,2.897251118784877,3.4389621293544628,3.328712052029376,5533.0,1402448494.1047335,1402448494.087039,1402448494.0836356

IFO: H , TRIGGERS: 1 found in a time window of  5 s around the maximum amplitude injection of type wnb_250_350_t100
trigger number: 580 , delay from inj: 4.087038993835449 s
TRIGGER parameters:

,gps,gpsPeak,duration,EnWDF,snrMean,snrPeak,freqMin,freqMean,freqMax,freqPeak,wave
580,1402448489.8203125,1402448490.0,0.00927734375,1.4391264761058726,1.3130133748001274,14.758109593276696,4.0,69.38461538461539,120.0,36.0,BsplineC206

IFO: L , TRIGGERS: 0 found in a time window of  5 s around the maximum amplitude injection of type wnb_250_350_t100
TRIGGER parameters:

Empty DataFrame
Columns: [gps, gpsPeak, duration, EnWDF, snrMean, snrPeak, freqMin, freqMean, freqMax, freqPeak, wave]
Index: []

--------------------------->INJECTION TYPE:  wnb_400_500_t30
maximum amplitude INJECTION parameters:

,amplitude,bandwidth,dec,duration,eccentricity,frequency,phase,pol,ra,seed,time,time_at_H1,time_at_L1
wnb_400_500_t30,1.0985064004362254e-37,100.0,-0.7090927312572702,0.03,0.8026279543342182,450.0,4.4090336818616676,5.400308679770101,0.4785326345222972,5533.0,1402437692.4047334,1402437692.4141767,1402437692.4177957

IFO: H , TRIGGERS: 1 found in a time window of  5 s around the maximum amplitude injection of type wnb_400_500_t30
trigger number: 90 , delay from inj: 2.4136884212493896 s
TRIGGER parameters:

,gps,gpsPeak,duration,EnWDF,snrMean,snrPeak,freqMin,freqMean,freqMax,freqPeak,wave
90,1402437689.953125,1402437690.0004883,0.00390625,1.7548272573789747,1.8909767438256115,23.611599704685137,12.0,62.0,112.0,20.0,BsplineC206

IFO: L , TRIGGERS: 0 found in a time window of  5 s around the maximum amplitude injection of type wnb_400_500_t30
TRIGGER parameters:

Empty DataFrame
Columns: [gps, gpsPeak, duration, EnWDF, snrMean, snrPeak, freqMin, freqMean, freqMax, freqPeak, wave]
Index: []

--------------------------->INJECTION TYPE:  wnb_100_120_t1000
maximum amplitude INJECTION parameters:

,amplitude,bandwidth,dec,duration,eccentricity,frequency,phase,pol,ra,seed,time,time_at_H1,time_at_L1
wnb_100_120_t1000,7.426322175573341e-38,20.0,-0.06406494958888888,1.0,0.4226508505090596,110.0,1.688758478634661,3.8803885486095346,4.791873064079817,5533.0,1402413812.108467,1402413812.1120615,1402413812.1206465

IFO: H , TRIGGERS: 0 found in a time window of  5 s around the maximum amplitude injection of type wnb_100_120_t1000
TRIGGER parameters:

Empty DataFrame
Columns: [gps, gpsPeak, duration, EnWDF, snrMean, snrPeak, freqMin, freqMean, freqMax, freqPeak, wave]
Index: []

IFO: L , TRIGGERS: 0 found in a time window of  5 s around the maximum amplitude injection of type wnb_100_120_t1000
TRIGGER parameters:

Empty DataFrame
Columns: [gps, gpsPeak, duration, EnWDF, snrMean, snrPeak, freqMin, freqMean, freqMax, freqPeak, wave]
Index: []

--------------------------->INJECTION TYPE:  wnb_295_305_t400
maximum amplitude INJECTION parameters:

,amplitude,bandwidth,dec,duration,eccentricity,frequency,phase,pol,ra,seed,time,time_at_H1,time_at_L1
wnb_295_305_t400,6.562028530961173e-38,10.0,-0.734666220887999,0.4,0.5880792951065662,300.0,3.1998512345981465,5.319442942774546,2.667109595661014,5533.0,1402466246.773795,1402466246.7823927,1402466246.785595

IFO: H , TRIGGERS: 1 found in a time window of  5 s around the maximum amplitude injection of type wnb_295_305_t400
trigger number: 1390 , delay from inj: 3.218095541000366 s
TRIGGER parameters:

,gps,gpsPeak,duration,EnWDF,snrMean,snrPeak,freqMin,freqMean,freqMax,freqPeak,wave
1390,1402466249.9140625,1402466250.0004883,0.0234375,0.5725669087169031,0.6476721877341117,7.4252859385085825,28.0,78.0,128.0,36.0,BsplineC206

IFO: L , TRIGGERS: 1 found in a time window of  5 s around the maximum amplitude injection of type wnb_295_305_t400
trigger number: 3903 , delay from inj: 2.214405059814453 s
TRIGGER parameters:

,gps,gpsPeak,duration,EnWDF,snrMean,snrPeak,freqMin,freqMean,freqMax,freqPeak,wave
3903,1402466248.8828125,1402466249.0,0.00390625,1.3228791830148292,1.034200816812252,16.381448577952984,140.0,190.0,240.0,168.0,BsplineC206

--------------------------->INJECTION TYPE:  wnb_80_90_t200
maximum amplitude INJECTION parameters:

,amplitude,bandwidth,dec,duration,eccentricity,frequency,phase,pol,ra,seed,time,time_at_H1,time_at_L1
wnb_80_90_t200,3.4178839488728417e-38,10.0,-1.0404112260739846,0.2,0.1303236925573562,85.0,0.0981650844632566,1.2392608511518273,5.100703436932842,5533.0,1402333924.2166963,1402333924.2323265,1402333924.2328043

IFO: H , TRIGGERS: 0 found in a time window of  5 s around the maximum amplitude injection of type wnb_80_90_t200
TRIGGER parameters:

Empty DataFrame
Columns: [gps, gpsPeak, duration, EnWDF, snrMean, snrPeak, freqMin, freqMean, freqMax, freqPeak, wave]
Index: []

IFO: L , TRIGGERS: 0 found in a time window of  5 s around the maximum amplitude injection of type wnb_80_90_t200
TRIGGER parameters:

Empty DataFrame
Columns: [gps, gpsPeak, duration, EnWDF, snrMean, snrPeak, freqMin, freqMean, freqMax, freqPeak, wave]
Index: []

--------------------------->INJECTION TYPE:  wnb_100_200_t100
maximum amplitude INJECTION parameters:

,amplitude,bandwidth,dec,duration,eccentricity,frequency,phase,pol,ra,seed,time,time_at_H1,time_at_L1
wnb_100_200_t100,2.5904886308517063e-38,100.0,-0.10230667527534433,0.1,0.10600013736342928,150.0,4.963929238901601,1.913116401414095,5.54841404160853,5533.0,1402244030.5541804,1402244030.5501726,1402244030.5572472

IFO: H , TRIGGERS: 1 found in a time window of  5 s around the maximum amplitude injection of type wnb_100_200_t100
trigger number: 12141 , delay from inj: 1.5496842861175537 s
TRIGGER parameters:

,gps,gpsPeak,duration,EnWDF,snrMean,snrPeak,freqMin,freqMean,freqMax,freqPeak,wave
12141,1402244028.9140625,1402244029.0004883,0.01025390625,1.9018971752255205,2.226671121241947,26.682624215975927,4.0,57.69230769230769,108.0,72.0,BsplineC309

IFO: L , TRIGGERS: 0 found in a time window of  5 s around the maximum amplitude injection of type wnb_100_200_t100
TRIGGER parameters:

Empty DataFrame
Columns: [gps, gpsPeak, duration, EnWDF, snrMean, snrPeak, freqMin, freqMean, freqMax, freqPeak, wave]
Index: []

--------------------------->INJECTION TYPE:  wnb_30_50_t1800
maximum amplitude INJECTION parameters:

,amplitude,bandwidth,dec,duration,eccentricity,frequency,phase,pol,ra,seed,time,time_at_H1,time_at_L1
wnb_30_50_t1800,2.1357822601759149e-38,20.0,0.016727086786663764,1.8,0.13075236725389372,40.0,3.5101143809839783,5.509729523949598,5.244397164720279,5533.0,1402308080.1382647,1402308080.1234498,1402308080.1209948

IFO: H , TRIGGERS: 0 found in a time window of  5 s around the maximum amplitude injection of type wnb_30_50_t1800
TRIGGER parameters:

Empty DataFrame
Columns: [gps, gpsPeak, duration, EnWDF, snrMean, snrPeak, freqMin, freqMean, freqMax, freqPeak, wave]
Index: []

IFO: L , TRIGGERS: 1 found in a time window of  5 s around the maximum amplitude injection of type wnb_30_50_t1800
trigger number: 12907 , delay from inj: 3.879005193710327 s
TRIGGER parameters:

,gps,gpsPeak,duration,EnWDF,snrMean,snrPeak,freqMin,freqMean,freqMax,freqPeak,wave
12907,1402308083.96875,1402308084.0,0.00341796875,0.5118012149364711,0.447203128757123,6.3186401299796575,148.0,198.0,248.0,208.0,Haar

--------------------------->INJECTION TYPE:  wnb_55_65_t500
maximum amplitude INJECTION parameters:

,amplitude,bandwidth,dec,duration,eccentricity,frequency,phase,pol,ra,seed,time,time_at_H1,time_at_L1
wnb_55_65_t500,7.27556104868897e-39,10.0,-0.08917874299731875,0.5,0.17038451961513013,60.0,0.09727857792008032,5.978927664287567,1.08750854577805,5533.0,1402319545.1941736,1402319545.1933384,1402319545.1840665

IFO: H , TRIGGERS: 0 found in a time window of  5 s around the maximum amplitude injection of type wnb_55_65_t500
TRIGGER parameters:

Empty DataFrame
Columns: [gps, gpsPeak, duration, EnWDF, snrMean, snrPeak, freqMin, freqMean, freqMax, freqPeak, wave]
Index: []

IFO: L , TRIGGERS: 0 found in a time window of  5 s around the maximum amplitude injection of type wnb_55_65_t500
TRIGGER parameters:

Empty DataFrame
Columns: [gps, gpsPeak, duration, EnWDF, snrMean, snrPeak, freqMin, freqMean, freqMax, freqPeak, wave]
Index: []

# Selected injections:


All with high SNR,
*   Very short injection (ga_1, ..., ga_100):
`inj_parameters['ga_100'].loc[98]`
*   ccsn:
`inj_parameters['ga_100'].loc[98]`
*   cbc_bbh125:
`inj_parameters['cbc_bbh125'].loc[105]`

Let's select the third highest amplitude inection of type `ga_100`:

In [71]:
inj_parameters['ga_100'].sort_values(by='amplitude', ascending=False).iloc[2]
#also by
#inj_parameters['ga_100'].loc[98]

time             1402228309.881055
ra               1.056891437519439
dec             0.9993716959996298
pol              4.348741504816312
amplitude   1.6970549821006593e-16
seed                        5533.0
duration                       0.1
Name: 98, dtype: float64

In [72]:
#so get time at the itfs as
time_ga100_98_atIFO = inj2ifo_time(inj_parameters['ga_100'].loc[98]['ra'], inj_parameters['ga_100'].loc[98]['dec'], inj_parameters['ga_100'].loc[98]['time'])
print("inj_parameters['ga_100'].loc[98]")
print("Time at H:", time_ga100_98_atIFO['H1'])
print("Time at L:", time_ga100_98_atIFO['L1'])

inj_parameters['ga_100'].loc[98]
Time at H: 1402228309.8696325
Time at L: 1402228309.8689678

In [73]:
inj_duration('ga_100')
print("duration:", inj_parameters['ga_100'].loc[98]['duration'], 's')

This injection type has no waveform described by a time series!
duration: 0.1 s

Let's take the highest amplitude injection from `ccsn_pan18_s402d-dd2`:

In [74]:
inj_parameters['ccsn_pan18_s402d-dd2'].sort_values(by='amplitude', ascending=False).iloc[0]
#also inj_parameters['ccsn_pan18_s402d-dd2'].loc[92]

time        1402265088.2911243
ra           4.985074553850091
dec         1.1350370134192302
pol         1.3457838921138343
amplitude    46.80541788218131
seed                    5533.0
Name: 92, dtype: float64

In [75]:
#so get time at the itfs as
time_ccsn_pan18_s402d_dd2_92_atIFO = inj2ifo_time(inj_parameters['ccsn_pan18_s402d-dd2'].loc[92]['ra'], inj_parameters['ccsn_pan18_s402d-dd2'].loc[92]['dec'], inj_parameters['ccsn_pan18_s402d-dd2'].loc[92]['time'])
print("inj_parameters['ccsn_pan18_s402d-dd2'].loc[92]")
print("Time at H:", time_ccsn_pan18_s402d_dd2_92_atIFO['H1'])
print("Time at L:", time_ccsn_pan18_s402d_dd2_92_atIFO['L1'])

inj_parameters['ccsn_pan18_s402d-dd2'].loc[92]
Time at H: 1402265088.2833533
Time at L: 1402265088.2875996

In [76]:
print("inj duration from time series for type ccsn_pan18_s402d-dd2:")
print(inj_duration('ccsn_pan18_s402d-dd2'), 's')

inj duration from time series for type ccsn_pan18_s402d-dd2:
94.77391148001057 s

Let's take highest amplitude inj of type `cbc_bbh125`:

In [77]:
inj_parameters['cbc_bbh125'].sort_values(by='amplitude', ascending=False).iloc[0]
#also inj_parameters['cbc_bbh125'].loc[105]

time         1402327559.321994
ra           6.253496171322681
dec         0.0840205511813443
pol         3.2840321996684776
amplitude   164.44454677050774
seed                    5533.0
Name: 105, dtype: float64

In [78]:
#so get time at the itfs as
time_cbc_bbh125_105_atIFO = inj2ifo_time(inj_parameters['cbc_bbh125'].loc[105]['ra'], inj_parameters['cbc_bbh125'].loc[105]['dec'], inj_parameters['cbc_bbh125'].loc[105]['time'])
print("inj_parameters['cbc_bbh125'].loc[105]")
print("Time at H:", time_cbc_bbh125_105_atIFO['H1'])
print("Time at L:", time_cbc_bbh125_105_atIFO['L1'])

inj_parameters['cbc_bbh125'].loc[105]
Time at H: 1402327559.3066525
Time at L: 1402327559.3081243

In [79]:
print("inj duration from time series for type cbc_bbh125:")
print(inj_duration('cbc_bbh125'), 's')

inj duration from time series for type cbc_bbh125:
2.0721435546875 s

### selecting ccsn inj with high snr

In [80]:
[wave_type for wave_type in inj_parameters_max_amp_df.index if 'ccsn' in wave_type]

['ccsn_pan18_s402d-dd2',
 'ccsn_pan21_s40fr',
 'ccsn_rad19_s10',
 'ccsn_and16_s20s',
 'ccsn_mez23_d15',
 'ccsn_pow21_z100',
 'ccsn_pow18_s18',
 'ccsn_and16_s20',
 'ccsn_oco18_mesa20pertlr',
 'ccsn_pow20_y20',
 'ccsn_mez23_d9',
 'ccsn_mor18_m13',
 'ccsn_pow23_m39-1e12',
 'ccsn_and19_s15fr']

In [81]:
ccsn_wave_types = [wave_type for wave_type in inj_parameters_max_amp_df.index if 'ccsn' in wave_type]
mask_ccsn = inj_parameters_max_amp_df.index
inj_parameters_max_amp_df.loc[ccsn_wave_types].sort_values(by='amplitude', ascending=False)

,amplitude,bandwidth,dec,duration,eccentricity,frequency,phase,pol,quality,ra,seed,time,time_at_H1,time_at_L1
ccsn_pan18_s402d-dd2,46.80541788218131,NaN,1.1350370134192302,NaN,NaN,NaN,NaN,1.3457838921138343,NaN,4.985074553850091,5533.0,1402265088.2911243,1402265088.2833533,1402265088.2875996
ccsn_pan21_s40fr,37.09340153372006,NaN,0.34313265791998454,NaN,NaN,NaN,NaN,0.3148485673882525,NaN,0.6646404911099573,5533.0,1402360714.3399901,1402360714.3406482,1402360714.3502567
ccsn_rad19_s10,9.626321196865183,NaN,-0.32136562421368314,NaN,NaN,NaN,NaN,2.0916972796428803,NaN,5.443197490092411,5533.0,1402283886.2370512,1402283886.2488406,1402283886.2408297
ccsn_and16_s20s,4.963481917641489,NaN,-0.5325391973932887,NaN,NaN,NaN,NaN,1.3113509163180495,NaN,5.833371369635343,5533.0,1402414826.3499827,1402414826.348803,1402414826.3509479
ccsn_mez23_d15,4.484278038815722,NaN,0.11088941735309783,NaN,NaN,NaN,NaN,4.007546467344519,NaN,5.085271592914525,5533.0,1402510095.6324604,1402510095.6392856,1402510095.6477
ccsn_pow21_z100,4.2718540685911375,NaN,0.520115679092806,NaN,NaN,NaN,NaN,1.6261394041355735,NaN,6.2752511925994705,5533.0,1402329468.2498376,1402329468.2304726,1402329468.2345915
ccsn_pow18_s18,3.7275758043187364,NaN,-0.5221963659300303,NaN,NaN,NaN,NaN,0.6992489779439639,NaN,4.531164377974312,5533.0,1402224311.1221492,1402224311.1205652,1402224311.1226268
ccsn_and16_s20,3.640478633532416,NaN,-0.2725506218160261,NaN,NaN,NaN,NaN,2.563629787141858,NaN,5.339998048930936,5533.0,1402270787.0115442,1402270787.0295422,1402270787.027981
ccsn_oco18_mesa20pertlr,3.293037142548756,NaN,0.07492665659407372,NaN,NaN,NaN,NaN,0.8621922046295688,NaN,1.4114300046850987,5533.0,1402404381.6006348,1402404381.6033862,1402404381.595659
ccsn_pow20_y20,3.1768657566183793,NaN,1.116862430843186,NaN,NaN,NaN,NaN,2.844234149557446,NaN,4.159996087381149,5533.0,1402487668.1879172,1402487668.1735704,1402487668.181481
ccsn_mez23_d9,2.9078296162406785,NaN,-1.1834095129541513,NaN,NaN,NaN,NaN,1.4405072499785099,NaN,2.8560402684340285,5533.0,1402213192.4692209,1402213192.4837172,1402213192.4828095
ccsn_mor18_m13,2.6805575687397827,NaN,0.9928645946282,NaN,NaN,NaN,NaN,3.7362898196994214,NaN,4.149845328185716,5533.0,1402486769.7969623,1402486769.782976,1402486769.7914634
ccsn_pow23_m39-1e12,1.6817989946655498,NaN,0.5410487622091144,NaN,NaN,NaN,NaN,5.858202277752373,NaN,4.475599641283558,5533.0,1402264681.2068934,1402264681.2092607,1402264681.208258
ccsn_and19_s15fr,0.09380638008967186,NaN,-0.7026897573183004,NaN,NaN,NaN,NaN,4.5709539560177435,NaN,4.329013690139793,5533.0,1402523838.2295496,1402523838.2471817,1402523838.2400935

In [82]:
inj_parameters['ccsn_pan18_s402d-dd2'].sort_values(by='amplitude', ascending=False)

,time,ra,dec,pol,amplitude,seed
92,1402265088.2911243,4.985074553850091,1.1350370134192302,1.3457838921138343,46.80541788218131,5533.0
114,1402402997.256765,1.7108314916069742,-1.000445343364793,4.1551026020587045,36.43205911084158,5533.0
98,1402323645.3167887,4.326875592545047,0.6565716288787146,0.8434583973517206,34.186328423144246,5533.0
127,1402520011.1484146,3.5999988031413444,-0.444921592123169,1.6721805622465808,29.975838704342685,5533.0
93,1402265301.5871384,2.2784092570409498,0.4877673539767966,3.8416520557153033,29.81204177832905,5533.0
87,1402233674.4077346,5.6079942795206,-0.9164697941081195,3.353275389927886,28.819771704756054,5533.0
124,1402503900.2693117,4.972453695445792,1.2046585976756592,0.9990423152911515,28.549105206537348,5533.0
99,1402324624.1353953,6.189353812878404,-0.13523171311431678,5.334010263828127,25.96744949158133,5533.0
101,1402342792.9154813,3.76383113109231,-0.49446368476374997,3.22373738943216,25.926995209264746,5533.0
108,1402379067.1589377,3.217499211344634,-0.5959067961854039,4.081608113969432,21.89570475706463,5533.0
107,1402372859.1559584,6.245457310317443,0.6083509367960002,3.639666423863419,20.084361850342848,5533.0
119,1402441170.585889,0.8701229984245944,0.11353408376180248,4.390202039470855,19.508084531485082,5533.0
100,1402330396.9192772,2.3443412180725023,-0.729173278855687,1.5246348207514018,18.37751857598053,5533.0
106,1402372757.8472965,1.3334093327462335,-0.7738009062501174,4.5651947346884665,18.32120890128648,5533.0
94,1402267322.1053555,3.187910295952261,0.684703388509135,4.445889899748368,17.887790238878654,5533.0
123,1402502366.0158474,1.883957595646952,0.8219222127799479,0.07043773338129701,17.86291043374577,5533.0
126,1402518882.8885553,3.9545558303991175,-0.9609859352091007,5.272474111992216,17.660316628866113,5533.0
116,1402409663.057855,0.30038197460140775,0.7894297477033997,3.1240921874238743,17.407509980155933,5533.0
109,1402379367.8407228,2.583499035576934,-0.051535706412341876,0.2225099823503415,16.38903675205013,5533.0
97,1402319974.3218696,2.0722714094717154,0.1406424633077205,3.9975196965591295,15.54088948175768,5533.0
111,1402393613.8421557,1.6311711551437726,0.276391960341099,0.6162139104335942,14.423709635785855,5533.0
88,1402243831.7339544,6.153224783453397,-0.6583851287713862,3.953699786064555,14.382534914188716,5533.0
96,1402298165.3347535,6.020263019281823,1.0691036222940227,3.873902540566799,13.721441552557494,5533.0
120,1402471176.0183144,3.150410798397095,-0.6193283556280935,0.09407705345824968,13.59216983552136,5533.0
113,1402398518.4116826,3.6776114580368837,-1.2909829816513683,5.375995714053906,13.463354648716622,5533.0
102,1402345128.1209064,3.8059027374367567,-1.081484685901282,0.9880169086511102,13.462402318820628,5533.0
95,1402281355.3291483,0.9248217041858607,-0.07518666890651686,5.175843072648779,13.177189100965661,5533.0
115,1402406688.5355246,5.032795015435125,0.8904581090245807,3.6033249417530153,12.427481071422573,5533.0
122,1402489503.8062832,1.8238392926125493,-0.8147102231457611,3.5684174451043797,12.401715493044852,5533.0
90,1402247443.2501895,2.779622319478269,-0.05560002227967074,1.802435820687997,11.864874623638698,5533.0
110,1402392451.0381367,1.7634146445893284,-0.46555990870713143,5.025746330488758,11.396832521122365,5533.0
121,1402485181.408035,3.2122067510586096,0.9847047570695561,2.572813828085119,10.993281224758471,5533.0
118,1402417480.7479725,4.00939696933363,0.8915516507141689,3.4743543244817983,10.863990959504592,5533.0
105,1402369659.2419536,0.12742960486646182,-0.7362032630896111,5.1789339957761795,10.797968667253382,5533.0
89,1402244327.6519668,3.3388353710094605,1.2963731212868728,2.4440100796689475,9.169212837046821,5533.0
117,1402416656.2547708,4.480202755475068,-0.15344283141969883,4.8127386028101995,8.947489563048883,5533.0
104,1402365236.1354516,4.494194287971132,-0.06534873642982071,4.089570373021222,8.180156232353665,5533.0
91,1402264378.4684706,0.6990075461468463,-0.06041336894416359,5.524127838847898,8.156220632204132,5533.0
86,1402231951.7349107,2.029808377733719,-1.0878066315616752,5.983263520880358,6.302604521967883,5533.0
103,1402360516.2620406,1.4942899850568492,0.8110888872251849,1.4144643944423567,6.285854709206963,5533.0
112,1402394006.1545908,3.662816656450979,-0.2896141221520002,4.57310366009962,5.3150203677523375,5533.0
125,1402508689.802657,2.28521385629337,0.015235826282735941,5.192606265577642,5.246377732516177,5533.0

### selecting short inj with high ampltiude

In [83]:
mask_short = inj_parameters_max_amp_df['duration'] < 1.
inj_parameters_max_amp_df[mask_short].sort_values(by='amplitude', ascending=False)

,amplitude,bandwidth,dec,duration,eccentricity,frequency,phase,pol,quality,ra,seed,time,time_at_H1,time_at_L1
ga_100,1.994540253969544e-16,NaN,-1.1514165528708418,0.1,NaN,NaN,NaN,3.6957906163861614,NaN,0.7996230162917786,5533.0,1402397283.7754822,1402397283.7905407,1402397283.7829256
ga_20,2.715934686207109e-20,NaN,1.1738824812375608,0.02,NaN,NaN,NaN,4.792634243939587,NaN,0.17177319496836016,5533.0,1402335239.2306128,1402335239.2119095,1402335239.2177355
ga_3,2.887139490407032e-22,NaN,0.7982272915261704,0.003,NaN,NaN,NaN,1.6183439788231966,NaN,0.26171958426613195,5533.0,1402485774.624565,1402485774.6083755,1402485774.6058788
ga_1,1.4710680826071645e-22,NaN,-1.3304068171871026,0.001,NaN,NaN,NaN,5.6252797285300735,NaN,3.2877168597827255,5533.0,1402360912.5626009,1402360912.5746262,1402360912.5687046
wnb_1220_1520_t500,6.378558632907808e-35,300.0,1.3918171972943447,0.5,0.6415628276200178,1370.0,5.5602434267526,3.494904360274674,NaN,1.003318495867917,5533.0,1402239805.5893328,1402239805.5725412,1402239805.5757031
wnb_1395_1405_t100,6.879192123620501e-36,10.0,-0.6255313994495769,0.1,0.9645047791821774,1400.0,2.3455110248553486,1.2809551080770805,NaN,4.616725682691891,5533.0,1402507605.832664,1402507605.8510518,1402507605.8536344
wnb_800_1000_t10,1.1094602486912695e-36,200.0,1.0378489591378561,0.01,0.4957653494097891,900.0,4.182799378412639,4.444968469244686,NaN,1.0589362172703265,5533.0,1402350956.880693,1402350956.8628356,1402350956.8698392
wnb_750_850_t100,1.0766345292885812e-36,100.0,-0.6648383711603701,0.1,0.11226566654657422,800.0,1.5466341401942587,6.061323066391147,NaN,4.686756021847648,5533.0,1402284521.8444858,1402284521.8507466,1402284521.8409636
wnb_250_350_t800,4.543039472454408e-37,100.0,-0.4908328075145552,0.8,0.1115327357938406,300.0,5.995668711207308,2.3967867905339717,NaN,5.188489318282579,5533.0,1402474443.4133298,1402474443.4092517,1402474443.4022293
wnb_400_450_t300,2.9562247963907372e-37,50.0,0.06748415830304533,0.3,0.6422955952771118,425.0,5.423118968065654,5.597107951670528,NaN,2.197470467302672,5533.0,1402294677.4789786,1402294677.483233,1402294677.4922254
wnb_250_350_t100,2.7877256571769102e-37,100.0,0.41379677066567416,0.1,0.38311541360511736,300.0,2.897251118784877,3.4389621293544628,NaN,3.328712052029376,5533.0,1402448494.1047335,1402448494.087039,1402448494.0836356
wnb_400_500_t30,1.0985064004362254e-37,100.0,-0.7090927312572702,0.03,0.8026279543342182,450.0,4.4090336818616676,5.400308679770101,NaN,0.4785326345222972,5533.0,1402437692.4047334,1402437692.4141767,1402437692.4177957
wnb_295_305_t400,6.562028530961173e-38,10.0,-0.734666220887999,0.4,0.5880792951065662,300.0,3.1998512345981465,5.319442942774546,NaN,2.667109595661014,5533.0,1402466246.773795,1402466246.7823927,1402466246.785595
wnb_80_90_t200,3.4178839488728417e-38,10.0,-1.0404112260739846,0.2,0.1303236925573562,85.0,0.0981650844632566,1.2392608511518273,NaN,5.100703436932842,5533.0,1402333924.2166963,1402333924.2323265,1402333924.2328043
wnb_100_200_t100,2.5904886308517063e-38,100.0,-0.10230667527534433,0.1,0.10600013736342928,150.0,4.963929238901601,1.913116401414095,NaN,5.54841404160853,5533.0,1402244030.5541804,1402244030.5501726,1402244030.5572472
wnb_55_65_t500,7.27556104868897e-39,10.0,-0.08917874299731875,0.5,0.17038451961513013,60.0,0.09727857792008032,5.978927664287567,NaN,1.08750854577805,5533.0,1402319545.1941736,1402319545.1933384,1402319545.1840665

In [84]:
inj_parameters['ga_100'].sort_values(by='amplitude', ascending=False)

,time,ra,dec,pol,amplitude,seed,duration
116,1402397283.7754822,0.7996230162917786,-1.1514165528708418,3.6957906163861614,1.994540253969544e-16,5533.0,0.1
110,1402332658.2450702,6.24573783833062,0.8330253029547856,2.7678017665554755,1.8810738341981743e-16,5533.0,0.1
98,1402228309.881055,1.056891437519439,0.9993716959996298,4.348741504816312,1.6970549821006593e-16,5533.0,0.1
119,1402409770.2171938,0.9360731156950961,0.8616266640204951,0.10171000791095232,1.605324018293499e-16,5533.0,0.1
102,1402249173.7027583,4.5777476002447735,0.30709194163246495,0.10567978413284584,1.4832365020747966e-16,5533.0,0.1
133,1402510988.3086734,0.44038639147287834,0.584614709036814,2.9345972892601324,1.4165814102161208e-16,5533.0,0.1
122,1402454198.969986,0.216471766590353,0.32769996279220515,4.060256757219871,1.3911708165660917e-16,5533.0,0.1
107,1402316765.2607918,4.488266280294372,-0.776511340997282,5.315830542388185,1.3417238038756367e-16,5533.0,0.1
128,1402491326.7502427,1.5339558122569292,-0.12581805832479054,2.4764557443317874,1.2842115698305946e-16,5533.0,0.1
101,1402247139.5077384,3.605733727193006,-0.3496437120327271,2.1947464978560194,1.2365332295119414e-16,5533.0,0.1
100,1402234563.7692447,0.4318331342370357,0.5386539768374042,4.295576649889921,9.431772743320933e-17,5533.0,0.1
109,1402325121.1054919,4.633784306757163,0.17078817921580836,6.161800765902216,9.33352428544652e-17,5533.0,0.1
105,1402265914.636809,3.6987215071631887,1.1490154062286266,0.9229031357683908,8.582163659602763e-17,5533.0,0.1
113,1402382783.3066132,0.22409110398647625,0.09396535860871923,1.5719245194249456,8.277850210449869e-17,5533.0,0.1
95,1402212387.3469923,4.417198106599086,-0.2724254499128769,4.289128631929082,7.452759732713238e-17,5533.0,0.1
129,1402491419.750723,5.54299959468072,-0.10120225291642669,3.0153847680360673,7.362836658581259e-17,5533.0,0.1
127,1402488985.4564228,2.0353650722920755,0.07595817528138973,2.070362584837717,7.155641560950499e-17,5533.0,0.1
124,1402469081.9656217,4.549224445618405,-0.15403650908201147,2.8554183258566197,6.831000562716543e-17,5533.0,0.1
99,1402232163.0215476,6.280893086159306,-0.7284889648468768,4.149286384804074,6.212313347581777e-17,5533.0,0.1
96,1402214242.1902518,6.264127170313199,-0.17351673063104414,2.0277468405043204,6.154047567259607e-17,5533.0,0.1
114,1402389308.0943356,1.6999374436999493,-0.6034899124177738,3.2707282117054057,5.946598346101617e-17,5533.0,0.1
118,1402409086.2239966,0.6009340749068692,0.4996285426243576,1.1544223616256601,5.859016736821287e-17,5533.0,0.1
94,1402207970.8436506,0.9983711651134588,-0.06365864108831917,2.5963442880769287,5.0291887289755206e-17,5533.0,0.1
130,1402495356.7702777,2.715871906950626,-0.8497916337885023,5.213840964634618,4.724616633004801e-17,5533.0,0.1
120,1402410680.361514,4.421264857248541,-0.3746058320883675,2.1994364957872414,4.661742482885978e-17,5533.0,0.1
104,1402258579.3072,2.7379634495372818,-0.5988012654910971,2.6987251302572277,4.480814958575569e-17,5533.0,0.1
123,1402468347.70207,0.3913515747674558,-0.41902622321576516,3.9618087594908458,4.2037149302845373e-17,5533.0,0.1
93,1402201982.5498264,3.604498575102054,1.3171484885945948,3.7868435983775988,4.202144807478362e-17,5533.0,0.1
111,1402332862.3555648,3.064943945274949,-0.4716215573328234,0.2906089896707985,3.5318612462313486e-17,5533.0,0.1
115,1402392360.2889898,4.3966729608652555,0.05618865966427726,4.883062615007057,3.288493645607485e-17,5533.0,0.1
132,1402507991.9805906,1.458307923628102,-0.790184189799684,4.257047548184323,3.1472863568298055e-17,5533.0,0.1
126,1402488586.4970956,2.7497174972562233,0.3660804316875381,3.31108501014523,2.93769643115373e-17,5533.0,0.1
97,1402228013.2099862,4.715673575000257,0.6343770779438781,1.1618263264003772,2.9315044780175736e-17,5533.0,0.1
108,1402321140.7888677,5.018846857627493,-0.6247474655210915,0.4877957432889121,2.834394612735151e-17,5533.0,0.1
117,1402404183.9050093,5.687753990740389,-0.029519718248761994,0.050020211264189686,2.4738216596950335e-17,5533.0,0.1
125,1402483369.9677145,1.476345128435709,0.02163364833999176,0.7498361070476263,2.4317701887172883e-17,5533.0,0.1
103,1402254169.6130333,1.4108710227344055,1.2343909584161816,4.55271583041122,2.4271662893571908e-17,5533.0,0.1
112,1402357408.0633352,0.4440060282912761,-0.2262206973279984,4.944453473553564,2.4133690169941388e-17,5533.0,0.1
131,1402495850.463339,4.195471473998171,0.5947088433331835,0.175070062389061,2.1534880027620333e-17,5533.0,0.1
106,1402279953.9359415,4.4461064072204355,0.30445546293051595,5.0449847834242085,2.1256526965016627e-17,5533.0,0.1
121,1402448296.8532038,1.803378723643117,-0.18728206606734285,0.09280626984231248,2.0727842082915595e-17,5533.0,0.1